/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penggajian.page.dashboard;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import penggajian.dao.TerDao;
import penggajian.dialog.JabatanDialog;
import penggajian.dialog.TerDialog;
import penggajian.helper.BaseSetting;
import penggajian.model.TerModel;

/**
 *
 * @author Dion
 */
public class GajiKotor extends javax.swing.JPanel {

    /**
     * Creates new form Home
     */
    public GajiKotor() {
        initComponents();
        
        BaseSetting.setTitlePage(titlePage);
        BaseSetting.setButton(add);
        BaseSetting.setButton(search);
        BaseSetting.setInput(searchInput);
        BaseSetting.setBoxPanel(panelGajiKotor);
        BaseSetting.setTitlePanel(titlePanelGajiKotor);

        BaseSetting.setTable(tableGajiKotor);
        
        loadTable("");

    }
    
    
    public void loadTable(String searchValue)
    {
        TerDao terDao = new TerDao();
        
        DefaultTableModel model = new DefaultTableModel();

        
        model.addColumn("ID");
        model.addColumn("Golongan");
        model.addColumn("Tarif");
        model.addColumn("Min");
        model.addColumn("Max");

        List<TerModel> results = terDao.getAllData(searchValue);
        for (TerModel j : results) {
            model.addRow(new Object[]{
                "#" + j.getId(),
                j.getGolongan(),
                j.getTarif(),
                BaseSetting.setRupiah(j.getMin()),
                BaseSetting.setRupiah(j.getMax()),
            });
        }

        tableGajiKotor.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePage = new javax.swing.JLabel();
        panelGajiKotor = new javax.swing.JPanel();
        titlePanelGajiKotor = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        add = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        search = new javax.swing.JButton();
        searchInput = new javax.swing.JTextField();
        export = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableGajiKotor = new javax.swing.JTable();

        titlePage.setText("Gaji Kotor");

        panelGajiKotor.setBackground(new java.awt.Color(204, 204, 204));

        titlePanelGajiKotor.setText("Semua Data TER");

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.BorderLayout());

        add.setText("Tambah");
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, java.awt.BorderLayout.LINE_START);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.BorderLayout(10, 0));

        search.setText("Search");
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMouseClicked(evt);
            }
        });
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel2.add(search, java.awt.BorderLayout.CENTER);

        searchInput.setToolTipText("");
        searchInput.setMinimumSize(new java.awt.Dimension(60, 26));
        searchInput.setPreferredSize(new java.awt.Dimension(60, 26));
        searchInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchInputActionPerformed(evt);
            }
        });
        jPanel2.add(searchInput, java.awt.BorderLayout.LINE_START);

        export.setText("Export");
        export.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exportMouseClicked(evt);
            }
        });
        export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportActionPerformed(evt);
            }
        });
        jPanel2.add(export, java.awt.BorderLayout.LINE_END);

        jPanel1.add(jPanel2, java.awt.BorderLayout.LINE_END);

        jScrollPane1.setVerifyInputWhenFocusTarget(false);

        tableGajiKotor.setAutoCreateRowSorter(true);
        tableGajiKotor.getTableHeader().setResizingAllowed(false);
        tableGajiKotor.getTableHeader().setReorderingAllowed(false);
        tableGajiKotor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableGajiKotorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableGajiKotor);

        javax.swing.GroupLayout panelGajiKotorLayout = new javax.swing.GroupLayout(panelGajiKotor);
        panelGajiKotor.setLayout(panelGajiKotorLayout);
        panelGajiKotorLayout.setHorizontalGroup(
            panelGajiKotorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePanelGajiKotor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
        );
        panelGajiKotorLayout.setVerticalGroup(
            panelGajiKotorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGajiKotorLayout.createSequentialGroup()
                .addComponent(titlePanelGajiKotor)
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGajiKotor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titlePage)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(titlePage)
                .addGap(20, 20, 20)
                .addComponent(panelGajiKotor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
//        BaseSetting.setDialog(new TerDialog(
//            new javax.swing.JFrame(), true, "Tambah", 0L, this));
    }//GEN-LAST:event_addMouseClicked

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addActionPerformed

    private void searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseClicked
        String searchInput = this.searchInput.getText();

        loadTable(searchInput);
    }//GEN-LAST:event_searchMouseClicked

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void searchInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchInputActionPerformed

    private void tableGajiKotorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableGajiKotorMouseClicked
        int barisTerpilih = tableGajiKotor.getSelectedRow();

        if(barisTerpilih != -1)
        {
            Long id = Long.parseLong(
                tableGajiKotor.getValueAt(barisTerpilih, 0)
                .toString()
                .replace("#", "")
            );

//            BaseSetting.setDialog(new TerDialog(
//                new javax.swing.JFrame(), true, "Edit", id, this));
        }
    }//GEN-LAST:event_tableGajiKotorMouseClicked

    private void exportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exportMouseClicked
        print();
    }//GEN-LAST:event_exportMouseClicked

    private void exportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exportActionPerformed
    
    public void print(){
        BaseSetting.exportTable(tableGajiKotor);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton export;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelGajiKotor;
    private javax.swing.JButton search;
    private javax.swing.JTextField searchInput;
    private javax.swing.JTable tableGajiKotor;
    private javax.swing.JLabel titlePage;
    private javax.swing.JLabel titlePanelGajiKotor;
    // End of variables declaration//GEN-END:variables
}
