/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penggajian.page.dashboard;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import penggajian.dao.JabatanDao;
import penggajian.helper.BaseSetting;

/**
 *
 * @author Dion
 */
public class Jabatan extends javax.swing.JPanel {

    /**
     * Creates new form Home
     */
    public Jabatan() {
        initComponents();
        
        BaseSetting.setTitlePage(titlePage, "Jabatan");
        
        BaseSetting.setBoxPanel(panelJabatan);
        BaseSetting.setTitlePanel(titlePanelJabatan, "Semua Jabatan");
        
        JabatanDao jabatan = new JabatanDao();

        BaseSetting.setTable(tableJabatan);
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Nama Jabatan");
        model.addColumn("Tunjangan");
        model.addColumn("Total Karyawan");

        List<Object[]> results = jabatan.getSemuaJabatan();
        for (Object[] row : results) {
            model.addRow(new Object[]{
                "#" + String.format("%02d", row[0]),
                row[1],
                BaseSetting.setRupiah((Long) row[2] ),
                row[3]
            });
        }

        tableJabatan.setModel(model);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePage = new javax.swing.JLabel();
        panelJabatan = new javax.swing.JPanel();
        titlePanelJabatan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableJabatan = new javax.swing.JTable();

        titlePage.setText("Jabatan");

        panelJabatan.setBackground(new java.awt.Color(204, 204, 204));

        titlePanelJabatan.setText("Title");

        jScrollPane1.setVerifyInputWhenFocusTarget(false);

        tableJabatan.setAutoCreateRowSorter(true);
        tableJabatan.getTableHeader().setResizingAllowed(false);
        tableJabatan.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableJabatan);

        javax.swing.GroupLayout panelJabatanLayout = new javax.swing.GroupLayout(panelJabatan);
        panelJabatan.setLayout(panelJabatanLayout);
        panelJabatanLayout.setHorizontalGroup(
            panelJabatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(titlePanelJabatan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelJabatanLayout.setVerticalGroup(
            panelJabatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJabatanLayout.createSequentialGroup()
                .addComponent(titlePanelJabatan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelJabatan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titlePage)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(titlePage)
                .addGap(20, 20, 20)
                .addComponent(panelJabatan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelJabatan;
    private javax.swing.JTable tableJabatan;
    private javax.swing.JLabel titlePage;
    private javax.swing.JLabel titlePanelJabatan;
    // End of variables declaration//GEN-END:variables
}
