/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penggajian.page.dashboard;

import java.io.InputStream;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import penggajian.dao.JabatanDao;
import penggajian.dialog.JabatanDialog;
import penggajian.helper.BaseSetting;
import penggajian.helper.DBConnetion;
import penggajian.model.JabatanModel;

/**
 *
 * @author Dion
 */
public class Jabatan extends javax.swing.JPanel {
    /**
     * Creates new form Home
     */
    public Jabatan() {
        

        initComponents();

        BaseSetting.setTitlePage(titlePage);
        
        BaseSetting.setButton(add);
        BaseSetting.setButton(search);
        BaseSetting.setInput(searchInput);
        BaseSetting.setBoxPanel(panelJabatan);
        BaseSetting.setTitlePanel(titlePanelJabatan);
        

        BaseSetting.setTable(tableJabatan);
        
        loadTable("");

    }
    
    
    public void loadTable(String searchValue)
    {
        JabatanDao jabatanDao = new JabatanDao();
        
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Nama Jabatan");
        model.addColumn("Tunjangan");
        model.addColumn("Total Karyawan");

        List<JabatanModel> results = jabatanDao.getAllData(searchValue);
        for (JabatanModel j : results) {
            model.addRow(new Object[]{
                "#" + j.getId(),
                j.getNama(),
                BaseSetting.setRupiah(j.getTunjangan()),
                j.getTotalKaryawan() + " orang",
            });
        }

        tableJabatan.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePage = new javax.swing.JLabel();
        panelJabatan = new javax.swing.JPanel();
        titlePanelJabatan = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        add = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        search = new javax.swing.JButton();
        searchInput = new javax.swing.JTextField();
        export = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableJabatan = new javax.swing.JTable();

        titlePage.setText("Jabatan");

        panelJabatan.setBackground(new java.awt.Color(204, 204, 204));

        titlePanelJabatan.setText("Semua Jabatan");

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.BorderLayout());

        add.setText("Tambah");
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, java.awt.BorderLayout.LINE_START);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.BorderLayout(10, 0));

        search.setText("Search");
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMouseClicked(evt);
            }
        });
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel2.add(search, java.awt.BorderLayout.CENTER);

        searchInput.setToolTipText("");
        searchInput.setMinimumSize(new java.awt.Dimension(60, 26));
        searchInput.setPreferredSize(new java.awt.Dimension(60, 26));
        searchInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchInputActionPerformed(evt);
            }
        });
        jPanel2.add(searchInput, java.awt.BorderLayout.LINE_START);

        export.setText("Export");
        export.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exportMouseClicked(evt);
            }
        });
        export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportActionPerformed(evt);
            }
        });
        jPanel2.add(export, java.awt.BorderLayout.LINE_END);

        jPanel1.add(jPanel2, java.awt.BorderLayout.LINE_END);

        jScrollPane1.setVerifyInputWhenFocusTarget(false);

        tableJabatan.setAutoCreateRowSorter(true);
        tableJabatan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableJabatan.getTableHeader().setResizingAllowed(false);
        tableJabatan.getTableHeader().setReorderingAllowed(false);
        tableJabatan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableJabatanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableJabatan);

        javax.swing.GroupLayout panelJabatanLayout = new javax.swing.GroupLayout(panelJabatan);
        panelJabatan.setLayout(panelJabatanLayout);
        panelJabatanLayout.setHorizontalGroup(
            panelJabatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJabatanLayout.createSequentialGroup()
                .addComponent(titlePanelJabatan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(85, 85, 85))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelJabatanLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelJabatanLayout.setVerticalGroup(
            panelJabatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJabatanLayout.createSequentialGroup()
                .addComponent(titlePanelJabatan)
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        jScrollPane1.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelJabatan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titlePage)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(titlePage)
                .addGap(20, 20, 20)
                .addComponent(panelJabatan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here: 
    }//GEN-LAST:event_searchActionPerformed

    private void searchInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchInputActionPerformed

    private void searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseClicked
        String searchInput = this.searchInput.getText();
        
        loadTable(searchInput);

    }//GEN-LAST:event_searchMouseClicked

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
        BaseSetting.setDialog(new JabatanDialog(
                new javax.swing.JFrame(), true, "Tambah", 0L, this));
    }//GEN-LAST:event_addMouseClicked

    private void tableJabatanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableJabatanMouseClicked
        int barisTerpilih = tableJabatan.getSelectedRow();
        
        if(barisTerpilih != -1)
        {
            Long id = Long.parseLong(
                tableJabatan.getValueAt(barisTerpilih, 0)
                    .toString()
                    .replace("#", "")
            );

            BaseSetting.setDialog(new JabatanDialog(
                    new javax.swing.JFrame(), true, "Edit", id, this));
        }
    }//GEN-LAST:event_tableJabatanMouseClicked

    private void exportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exportActionPerformed

    private void exportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exportMouseClicked
        print();
    }//GEN-LAST:event_exportMouseClicked

    public void print(){
        try {
            InputStream reportStream = getClass().getResourceAsStream("/penggajian/jasper/jabatan.jasper");        
            if (reportStream == null) {
                JOptionPane.showMessageDialog(this, "File .jasper tidak ditemukan");
                return;
            }
            Map<String, Object> parameter = new HashMap<>();
            java.net.URL imgURL = getClass().getResource("/penggajian/img/logo.png");
            parameter.put("BRAND_LOGO", imgURL); 
            parameter.put("BRAND_NAME", BaseSetting.getBrand()); 
            
            java.sql.Connection conn = DBConnetion.getConnection();
            JasperPrint jp = JasperFillManager.fillReport(reportStream, parameter, conn);
            JasperViewer.viewReport(jp, false);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal: " + e.getMessage());
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton export;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelJabatan;
    private javax.swing.JButton search;
    private javax.swing.JTextField searchInput;
    private javax.swing.JTable tableJabatan;
    private javax.swing.JLabel titlePage;
    private javax.swing.JLabel titlePanelJabatan;
    // End of variables declaration//GEN-END:variables
}
