/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penggajian.page;

import java.awt.CardLayout;
import penggajian.helper.BaseSetting;
import penggajian.page.dashboard.*;

/**
 *
 * @author Dion
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    Home home = new Home();
    Jabatan jabatan = new Jabatan();
    Ter ter = new Ter();
    Bpjs bpjs = new Bpjs();
    Karyawan karyawan = new Karyawan();
    GajiKotor gajiKotor = new GajiKotor();
    GajiBersih gajiBersih = new GajiBersih();

    
    CardLayout clInner = new CardLayout();

    public Dashboard() {
        BaseSetting.applyFrame(this);
        initComponents();

        innerContent.setLayout(clInner);
        innerContent.add(home, "home");
        innerContent.add(ter, "ter");
        innerContent.add(jabatan, "jabatan");
        innerContent.add(bpjs, "bpjs");
        innerContent.add(karyawan, "karyawan");
        innerContent.add(gajiKotor, "gajiKotor");
        innerContent.add(gajiBersih, "gajiBersih");

        clInner.show(innerContent, "gajiBersih");
        
        brand.setText(BaseSetting.getBrand());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        brand = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        menuHome = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        menuJabatan = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        printJabatan = new javax.swing.JLabel();
        menuTer = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        printTer = new javax.swing.JLabel();
        menuBpjs = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        menuKaryawan = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        printKaryawan = new javax.swing.JLabel();
        menuGaji = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        menuGajiKotor = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        printGajiKotor = new javax.swing.JLabel();
        menuGajiBersih = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        printGajiBersih = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        menuLogout = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        mainContent = new javax.swing.JPanel();
        innerContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));

        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setOpaque(false);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penggajian/img/logo.png"))); // NOI18N
        jLabel2.setAutoscrolls(true);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel2);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SISTEM PENGGAJIAN");
        jLabel1.setFocusable(false);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel1);

        brand.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        brand.setForeground(new java.awt.Color(255, 255, 255));
        brand.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        brand.setText("Get the Brand");
        brand.setFocusable(false);
        brand.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(brand);

        jPanel21.setMaximumSize(new java.awt.Dimension(32767, 264));
        jPanel21.setOpaque(false);

        menuHome.setBackground(new java.awt.Color(51, 0, 153));
        menuHome.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 20));
        menuHome.setMinimumSize(new java.awt.Dimension(141, 34));
        menuHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuHomeMouseClicked(evt);
            }
        });
        menuHome.setLayout(new java.awt.BorderLayout());

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 25, 12));

        jLabel40.setBackground(new java.awt.Color(0, 51, 51));
        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penggajian/img/home.png"))); // NOI18N
        jPanel3.add(jLabel40);

        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Home");
        jPanel3.add(jLabel41);

        menuHome.add(jPanel3, java.awt.BorderLayout.WEST);
        jPanel3.getAccessibleContext().setAccessibleName("");

        menuJabatan.setBackground(new java.awt.Color(51, 0, 153));
        menuJabatan.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 20));
        menuJabatan.setMinimumSize(new java.awt.Dimension(141, 34));
        menuJabatan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuJabatanMouseClicked(evt);
            }
        });
        menuJabatan.setLayout(new java.awt.BorderLayout());

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 25, 12));

        jLabel55.setBackground(new java.awt.Color(0, 51, 51));
        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penggajian/img/jabatan.png"))); // NOI18N
        jPanel4.add(jLabel55);

        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText("Jabatan");
        jPanel4.add(jLabel56);

        menuJabatan.add(jPanel4, java.awt.BorderLayout.WEST);

        printJabatan.setBackground(new java.awt.Color(0, 51, 51));
        printJabatan.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        printJabatan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penggajian/img/print.png"))); // NOI18N
        printJabatan.setToolTipText("");
        printJabatan.setAlignmentX(0.5F);
        printJabatan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printJabatanMouseClicked(evt);
            }
        });
        menuJabatan.add(printJabatan, java.awt.BorderLayout.EAST);

        menuTer.setBackground(new java.awt.Color(51, 0, 153));
        menuTer.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 20));
        menuTer.setMinimumSize(new java.awt.Dimension(141, 34));
        menuTer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuTerMouseClicked(evt);
            }
        });
        menuTer.setLayout(new java.awt.BorderLayout());

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 25, 12));

        jLabel58.setBackground(new java.awt.Color(0, 51, 51));
        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penggajian/img/ter.png"))); // NOI18N
        jPanel5.add(jLabel58);

        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("Ter");
        jPanel5.add(jLabel59);

        menuTer.add(jPanel5, java.awt.BorderLayout.WEST);

        printTer.setBackground(new java.awt.Color(0, 51, 51));
        printTer.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        printTer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penggajian/img/print.png"))); // NOI18N
        printTer.setToolTipText("");
        printTer.setAlignmentX(0.5F);
        printTer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printTerMouseClicked(evt);
            }
        });
        menuTer.add(printTer, java.awt.BorderLayout.EAST);

        menuBpjs.setBackground(new java.awt.Color(51, 0, 153));
        menuBpjs.setMinimumSize(new java.awt.Dimension(141, 34));
        menuBpjs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBpjsMouseClicked(evt);
            }
        });
        menuBpjs.setLayout(new java.awt.BorderLayout());

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 25, 12));

        jLabel46.setBackground(new java.awt.Color(0, 51, 51));
        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penggajian/img/bpjs.png"))); // NOI18N
        jPanel6.add(jLabel46);

        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("BPJS");
        jPanel6.add(jLabel47);

        menuBpjs.add(jPanel6, java.awt.BorderLayout.WEST);

        menuKaryawan.setBackground(new java.awt.Color(51, 0, 153));
        menuKaryawan.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 20));
        menuKaryawan.setMinimumSize(new java.awt.Dimension(141, 34));
        menuKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuKaryawanMouseClicked(evt);
            }
        });
        menuKaryawan.setLayout(new java.awt.BorderLayout());

        jPanel7.setOpaque(false);
        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 25, 12));

        jLabel48.setBackground(new java.awt.Color(0, 51, 51));
        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penggajian/img/karyawan.png"))); // NOI18N
        jPanel7.add(jLabel48);

        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("Karyawan");
        jPanel7.add(jLabel49);

        menuKaryawan.add(jPanel7, java.awt.BorderLayout.WEST);

        printKaryawan.setBackground(new java.awt.Color(0, 51, 51));
        printKaryawan.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        printKaryawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penggajian/img/print.png"))); // NOI18N
        printKaryawan.setToolTipText("");
        printKaryawan.setAlignmentX(0.5F);
        printKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printKaryawanMouseClicked(evt);
            }
        });
        menuKaryawan.add(printKaryawan, java.awt.BorderLayout.EAST);

        menuGaji.setBackground(new java.awt.Color(51, 0, 153));
        menuGaji.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 20));
        menuGaji.setMinimumSize(new java.awt.Dimension(141, 34));
        menuGaji.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuGajiMouseClicked(evt);
            }
        });
        menuGaji.setLayout(new java.awt.BorderLayout());

        jPanel8.setOpaque(false);
        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 25, 12));

        jLabel52.setBackground(new java.awt.Color(0, 51, 51));
        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penggajian/img/gaji.png"))); // NOI18N
        jPanel8.add(jLabel52);

        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("Gaji");
        jPanel8.add(jLabel53);

        menuGaji.add(jPanel8, java.awt.BorderLayout.WEST);

        menuGajiKotor.setBackground(new java.awt.Color(51, 0, 153));
        menuGajiKotor.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 40, 0, 20));
        menuGajiKotor.setMinimumSize(new java.awt.Dimension(141, 34));
        menuGajiKotor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuGajiKotorMouseClicked(evt);
            }
        });
        menuGajiKotor.setLayout(new java.awt.BorderLayout());

        jPanel10.setOpaque(false);
        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 25, 12));

        jLabel54.setBackground(new java.awt.Color(0, 51, 51));
        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penggajian/img/arrow-right.png"))); // NOI18N
        jPanel10.add(jLabel54);

        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setText("Gaji Kotor");
        jPanel10.add(jLabel57);

        menuGajiKotor.add(jPanel10, java.awt.BorderLayout.WEST);

        printGajiKotor.setBackground(new java.awt.Color(0, 51, 51));
        printGajiKotor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        printGajiKotor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penggajian/img/print.png"))); // NOI18N
        printGajiKotor.setToolTipText("");
        printGajiKotor.setAlignmentX(0.5F);
        printGajiKotor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printGajiKotorMouseClicked(evt);
            }
        });
        menuGajiKotor.add(printGajiKotor, java.awt.BorderLayout.EAST);

        menuGajiBersih.setBackground(new java.awt.Color(51, 0, 153));
        menuGajiBersih.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 40, 0, 20));
        menuGajiBersih.setMinimumSize(new java.awt.Dimension(141, 34));
        menuGajiBersih.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuGajiBersihMouseClicked(evt);
            }
        });
        menuGajiBersih.setLayout(new java.awt.BorderLayout());

        jPanel11.setOpaque(false);
        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 25, 12));

        jLabel60.setBackground(new java.awt.Color(0, 51, 51));
        jLabel60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penggajian/img/arrow-right.png"))); // NOI18N
        jPanel11.add(jLabel60);

        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setText("Gaji Bersih");
        jPanel11.add(jLabel61);

        menuGajiBersih.add(jPanel11, java.awt.BorderLayout.WEST);

        printGajiBersih.setBackground(new java.awt.Color(0, 51, 51));
        printGajiBersih.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        printGajiBersih.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penggajian/img/print.png"))); // NOI18N
        printGajiBersih.setToolTipText("");
        printGajiBersih.setAlignmentX(0.5F);
        printGajiBersih.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printGajiBersihMouseClicked(evt);
            }
        });
        menuGajiBersih.add(printGajiBersih, java.awt.BorderLayout.EAST);

        jPanel25.setBackground(new java.awt.Color(79, 22, 192));
        jPanel25.setAlignmentX(0.1F);
        jPanel25.setAlignmentY(0.1F);
        jPanel25.setAutoscrolls(true);
        jPanel25.setMinimumSize(new java.awt.Dimension(141, 34));
        jPanel25.setPreferredSize(new java.awt.Dimension(5, 10));
        jPanel25.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 25, 5));

        menuLogout.setBackground(new java.awt.Color(51, 0, 153));
        menuLogout.setMinimumSize(new java.awt.Dimension(141, 34));
        menuLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLogoutMouseClicked(evt);
            }
        });
        menuLogout.setLayout(new java.awt.BorderLayout());

        jPanel9.setOpaque(false);
        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 25, 12));

        jLabel64.setBackground(new java.awt.Color(0, 51, 51));
        jLabel64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penggajian/img/logout.png"))); // NOI18N
        jPanel9.add(jLabel64);

        jLabel65.setForeground(new java.awt.Color(255, 255, 255));
        jLabel65.setText("Logout");
        jPanel9.add(jLabel65);

        menuLogout.add(jPanel9, java.awt.BorderLayout.WEST);

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuJabatan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuTer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuBpjs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuKaryawan, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
            .addComponent(menuGaji, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuGajiKotor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuGajiBersih, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addComponent(menuHome, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuTer, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuBpjs, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuGaji, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(menuGajiKotor, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(menuGajiBersih, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menuLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);
        jPanel1.getAccessibleContext().setAccessibleName("");

        mainContent.setBorder(javax.swing.BorderFactory.createEmptyBorder(40, 40, 40, 40));
        mainContent.setLayout(new java.awt.CardLayout());

        innerContent.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout innerContentLayout = new javax.swing.GroupLayout(innerContent);
        innerContent.setLayout(innerContentLayout);
        innerContentLayout.setHorizontalGroup(
            innerContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        innerContentLayout.setVerticalGroup(
            innerContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1103, Short.MAX_VALUE)
        );

        mainContent.add(innerContent, "card2");

        getContentPane().add(mainContent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHomeMouseClicked
        clInner.show(innerContent, "home");
    }//GEN-LAST:event_menuHomeMouseClicked

    private void menuJabatanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuJabatanMouseClicked
        clInner.show(innerContent, "jabatan");
    }//GEN-LAST:event_menuJabatanMouseClicked

    private void menuLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMouseClicked
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuLogoutMouseClicked

    private void menuBpjsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBpjsMouseClicked
        clInner.show(innerContent, "bpjs");
    }//GEN-LAST:event_menuBpjsMouseClicked

    private void menuKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuKaryawanMouseClicked
        clInner.show(innerContent, "karyawan");
    }//GEN-LAST:event_menuKaryawanMouseClicked

    private void menuGajiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuGajiMouseClicked
//        clInner.show(innerContent, "gaji");
    }//GEN-LAST:event_menuGajiMouseClicked

    private void menuTerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTerMouseClicked
        clInner.show(innerContent, "ter");
    }//GEN-LAST:event_menuTerMouseClicked

    private void printJabatanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printJabatanMouseClicked
        jabatan.print();
    }//GEN-LAST:event_printJabatanMouseClicked

    private void printTerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printTerMouseClicked
        ter.print();
    }//GEN-LAST:event_printTerMouseClicked

    private void printKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printKaryawanMouseClicked
        karyawan.print();
    }//GEN-LAST:event_printKaryawanMouseClicked

    private void printGajiKotorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printGajiKotorMouseClicked
        gajiKotor.print();
    }//GEN-LAST:event_printGajiKotorMouseClicked

    private void menuGajiKotorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuGajiKotorMouseClicked
       clInner.show(innerContent, "gajiKotor");
    }//GEN-LAST:event_menuGajiKotorMouseClicked

    private void printGajiBersihMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printGajiBersihMouseClicked
        gajiBersih.print();
    }//GEN-LAST:event_printGajiBersihMouseClicked

    private void menuGajiBersihMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuGajiBersihMouseClicked
        clInner.show(innerContent, "gajiBersih");
    }//GEN-LAST:event_menuGajiBersihMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel brand;
    private javax.swing.JPanel innerContent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel mainContent;
    private javax.swing.JPanel menuBpjs;
    private javax.swing.JPanel menuGaji;
    private javax.swing.JPanel menuGajiBersih;
    private javax.swing.JPanel menuGajiKotor;
    private javax.swing.JPanel menuHome;
    private javax.swing.JPanel menuJabatan;
    private javax.swing.JPanel menuKaryawan;
    private javax.swing.JPanel menuLogout;
    private javax.swing.JPanel menuTer;
    private javax.swing.JLabel printGajiBersih;
    private javax.swing.JLabel printGajiKotor;
    private javax.swing.JLabel printJabatan;
    private javax.swing.JLabel printKaryawan;
    private javax.swing.JLabel printTer;
    // End of variables declaration//GEN-END:variables
}
