/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penggajian.page;

import java.awt.CardLayout;
import penggajian.helper.BaseSetting;
import penggajian.page.dashboard.*;

/**
 *
 * @author Dion
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    Home home = new Home();
    Ter ter = new Ter();
    Jabatan jabatan = new Jabatan();
    Bpjs bpjs = new Bpjs();
    Karyawan karyawan = new Karyawan();
    Gaji gaji = new Gaji();

    CardLayout cl = new CardLayout();

    public Dashboard() {
        BaseSetting.applyFrame(this);
        initComponents();

        mainContent.setLayout(cl);

        mainContent.add(home, "home");
        mainContent.add(ter, "ter");
        mainContent.add(jabatan, "jabatan");
        mainContent.add(bpjs, "bpjs");
        mainContent.add(karyawan, "karyawan");
        mainContent.add(gaji, "gaji");

        cl.show(mainContent, "home");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        menuHome = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        menuTer = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        menuJabatan = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        menuBpjs = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        menuKaryawan = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        menuLogout = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        menuGaji = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        mainContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));

        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setOpaque(false);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penggajian/img/logo.png"))); // NOI18N
        jLabel2.setAutoscrolls(true);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel2);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SISTEM PENGGAJIAN");
        jLabel1.setFocusable(false);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel1);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CV. Anugrah Berkah Cemerlang");
        jLabel4.setFocusable(false);
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel4);

        jPanel21.setMaximumSize(new java.awt.Dimension(32767, 264));
        jPanel21.setOpaque(false);

        menuHome.setBackground(new java.awt.Color(51, 0, 153));
        menuHome.setMinimumSize(new java.awt.Dimension(141, 34));
        menuHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuHomeMouseClicked(evt);
            }
        });
        menuHome.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 25, 5));

        jLabel40.setBackground(new java.awt.Color(0, 51, 51));
        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penggajian/img/home.png"))); // NOI18N
        menuHome.add(jLabel40);

        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Home");
        menuHome.add(jLabel41);

        menuTer.setBackground(new java.awt.Color(51, 0, 153));
        menuTer.setMinimumSize(new java.awt.Dimension(141, 34));
        menuTer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuTerMouseClicked(evt);
            }
        });
        menuTer.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 25, 5));

        jLabel42.setBackground(new java.awt.Color(0, 51, 51));
        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penggajian/img/ter.png"))); // NOI18N
        menuTer.add(jLabel42);

        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("TER");
        menuTer.add(jLabel43);

        menuJabatan.setBackground(new java.awt.Color(51, 0, 153));
        menuJabatan.setMinimumSize(new java.awt.Dimension(141, 34));
        menuJabatan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuJabatanMouseClicked(evt);
            }
        });
        menuJabatan.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 25, 5));

        jLabel44.setBackground(new java.awt.Color(0, 51, 51));
        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penggajian/img/jabatan.png"))); // NOI18N
        menuJabatan.add(jLabel44);

        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Jabatan");
        menuJabatan.add(jLabel45);

        menuBpjs.setBackground(new java.awt.Color(51, 0, 153));
        menuBpjs.setMinimumSize(new java.awt.Dimension(141, 34));
        menuBpjs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBpjsMouseClicked(evt);
            }
        });
        menuBpjs.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 25, 5));

        jLabel46.setBackground(new java.awt.Color(0, 51, 51));
        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penggajian/img/bpjs.png"))); // NOI18N
        menuBpjs.add(jLabel46);

        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("BPJS");
        menuBpjs.add(jLabel47);

        menuKaryawan.setBackground(new java.awt.Color(51, 0, 153));
        menuKaryawan.setMinimumSize(new java.awt.Dimension(141, 34));
        menuKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuKaryawanMouseClicked(evt);
            }
        });
        menuKaryawan.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 25, 5));

        jLabel48.setBackground(new java.awt.Color(0, 51, 51));
        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penggajian/img/karyawan.png"))); // NOI18N
        menuKaryawan.add(jLabel48);

        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("Karyawan");
        menuKaryawan.add(jLabel49);

        menuLogout.setBackground(new java.awt.Color(51, 0, 153));
        menuLogout.setMinimumSize(new java.awt.Dimension(141, 34));
        menuLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLogoutMouseClicked(evt);
            }
        });
        menuLogout.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 25, 5));

        jLabel50.setBackground(new java.awt.Color(0, 51, 51));
        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penggajian/img/logout.png"))); // NOI18N
        menuLogout.add(jLabel50);

        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("Logout");
        menuLogout.add(jLabel51);

        jPanel25.setBackground(new java.awt.Color(79, 22, 192));
        jPanel25.setAlignmentX(0.1F);
        jPanel25.setAlignmentY(0.1F);
        jPanel25.setAutoscrolls(true);
        jPanel25.setMinimumSize(new java.awt.Dimension(141, 34));
        jPanel25.setPreferredSize(new java.awt.Dimension(5, 10));
        jPanel25.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 25, 5));

        menuGaji.setBackground(new java.awt.Color(51, 0, 153));
        menuGaji.setMinimumSize(new java.awt.Dimension(141, 34));
        menuGaji.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuGajiMouseClicked(evt);
            }
        });
        menuGaji.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 25, 5));

        jLabel52.setBackground(new java.awt.Color(0, 51, 51));
        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penggajian/img/gaji.png"))); // NOI18N
        menuGaji.add(jLabel52);

        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("Gaji");
        menuGaji.add(jLabel53);

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(menuKaryawan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuBpjs, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuJabatan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(menuHome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuTer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuGaji, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 335, Short.MAX_VALUE))
            .addComponent(jPanel25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addComponent(menuLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(307, 307, 307))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addComponent(menuHome, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuTer, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuBpjs, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuGaji, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menuLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);
        jPanel1.getAccessibleContext().setAccessibleName("");

        mainContent.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout mainContentLayout = new javax.swing.GroupLayout(mainContent);
        mainContent.setLayout(mainContentLayout);
        mainContentLayout.setHorizontalGroup(
            mainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 445, Short.MAX_VALUE)
        );
        mainContentLayout.setVerticalGroup(
            mainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1219, Short.MAX_VALUE)
        );

        getContentPane().add(mainContent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHomeMouseClicked
        cl.show(mainContent, "home");
    }//GEN-LAST:event_menuHomeMouseClicked

    private void menuTerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTerMouseClicked
        cl.show(mainContent, "ter");
    }//GEN-LAST:event_menuTerMouseClicked

    private void menuLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMouseClicked
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuLogoutMouseClicked

    private void menuJabatanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuJabatanMouseClicked
        cl.show(mainContent, "jabatan");
    }//GEN-LAST:event_menuJabatanMouseClicked

    private void menuBpjsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBpjsMouseClicked
        cl.show(mainContent, "bpjs");
    }//GEN-LAST:event_menuBpjsMouseClicked

    private void menuKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuKaryawanMouseClicked
        cl.show(mainContent, "karyawan");
    }//GEN-LAST:event_menuKaryawanMouseClicked

    private void menuGajiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuGajiMouseClicked
        cl.show(mainContent, "gaji");
    }//GEN-LAST:event_menuGajiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel mainContent;
    private javax.swing.JPanel menuBpjs;
    private javax.swing.JPanel menuGaji;
    private javax.swing.JPanel menuHome;
    private javax.swing.JPanel menuJabatan;
    private javax.swing.JPanel menuKaryawan;
    private javax.swing.JPanel menuLogout;
    private javax.swing.JPanel menuTer;
    // End of variables declaration//GEN-END:variables
}
