/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penggajian.dialog;

import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import penggajian.dao.BpjsDao;
import penggajian.dao.GajiBersihDao;
import penggajian.dao.GajiKotorDao;
import penggajian.dao.JabatanDao;
import penggajian.dao.KaryawanDao;
import penggajian.dao.TerDao;
import penggajian.helper.BaseSetting;
import penggajian.model.BpjsModel;
import penggajian.model.GajiBersihModel;
import penggajian.model.GajiKotorModel;
import penggajian.model.JabatanModel;
import penggajian.model.KaryawanModel;
import penggajian.model.TerModel;
import penggajian.page.dashboard.GajiBersih;

/**
 *
 * @author Dion
 */
public class GajiBersihDialog extends javax.swing.JDialog {
    private GajiBersih panel;
    /**
     * Creates new form JabatanDialog
     */
    public GajiBersihDialog(java.awt.Frame parent, boolean modal, String typeDialog, Long id, GajiBersih panel) {
        super(parent, modal);
        this.panel = panel;
        initComponents();
        
        BaseSetting.setTitlePanel(title);
        title.setText(
            typeDialog + " " + title.getText()
        );
        
        BaseSetting.setInput(inputId);
        inputId.setEditable(false);
        BaseSetting.setInput(inputGajiKotorId);
        BaseSetting.setInput(inputGPokok);
        inputGPokok.setEditable(false);
        BaseSetting.setInput(inputGKotor);
        inputGKotor.setEditable(false);
        BaseSetting.setCombo(comboKaryawan);
        comboKaryawan.setEnabled(false);
        
        BaseSetting.setInput(inputPotonganAbsen);
        inputPotonganAbsen.setEditable(false);
        BaseSetting.setInput(inputJumlahAbsen);
        BaseSetting.setInput(inputJht);
        inputJht.setEditable(false);
 
        BaseSetting.setCombo(comboBulan);
        comboBulan.setEnabled(false);
        BaseSetting.setInput(inputTahun);
        inputTahun.setEditable(false);

        
        
        BaseSetting.setButton(save);
        BaseSetting.setButton(edit);
        BaseSetting.setButton(delete);

        if(typeDialog.equals("Edit")){
            save.setVisible(false);
            edit.setVisible(true);
            delete.setVisible(true);
            
            GajiBersihDao gajiBersihDao = new GajiBersihDao();
            GajiBersihModel gajiBersihModel = gajiBersihDao.getById(id);
            
            inputId.setText("#" + gajiBersihModel.getId());
            inputGajiKotorId.setText("#" + gajiBersihModel.getGajiKotorId());
            inputGajiKotorId.setEditable(false);
            
            inputGPokok.setText("" + 
                    gajiBersihModel.getGajiKotorModel().getGajiPokok());
            inputGKotor.setText("" + 
                    gajiBersihModel.getGajiKotorModel().getTotal());
            comboBulan.setSelectedItem(gajiBersihModel.getBulan());
            inputTahun.setText("" + gajiBersihModel.getTahun());
            comboKaryawan.setEnabled(false);
            inputPotonganAbsen.setText("" + gajiBersihModel.getPotonganAbsen());
            inputJumlahAbsen.setText("" + gajiBersihModel.getJumlahAbsen());
            
            inputJht.setText("" + gajiBersihModel.getJht());
            
            comboBulan.setSelectedItem(gajiBersihModel.getBulan());
            inputTahun.setText("" + gajiBersihModel.getTahun());
            
            KaryawanModel karyawanTarget = gajiBersihModel.getKaryawanModel();
            loadComboKaryawan();
            for (int i = 0; i < comboKaryawan.getItemCount(); i++) {
                KaryawanModel item = comboKaryawan.getItemAt(i);

                if (item.getId() == karyawanTarget.getId()) {
                    comboKaryawan.setSelectedIndex(i);
                    break;
                }
            }
            

        }else{
            save.setVisible(true);
            edit.setVisible(false);
            delete.setVisible(false);
        }
    }
    
    private void loadComboKaryawan() {
        comboKaryawan.removeAllItems();

        try {
            KaryawanDao karyawanDao = new KaryawanDao(); 
            List<KaryawanModel> listKaryawan = karyawanDao.getAllData("", false); 

            for (KaryawanModel k : listKaryawan) {
                comboKaryawan.addItem(k); 
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        labelGPokok1 = new javax.swing.JLabel();
        inputId = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        labelGPokok2 = new javax.swing.JLabel();
        inputGajiKotorId = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        labelGPokok3 = new javax.swing.JLabel();
        inputGPokok = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        labelGolongan3 = new javax.swing.JLabel();
        comboKaryawan = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        labelGPokok = new javax.swing.JLabel();
        inputGKotor = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        labelTunjanganJabatan = new javax.swing.JLabel();
        inputPotonganAbsen = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        labelTunjanganLembur = new javax.swing.JLabel();
        inputJumlahAbsen = new javax.swing.JTextField();
        jPanel20 = new javax.swing.JPanel();
        labelTunjanganLembur3 = new javax.swing.JLabel();
        inputJht = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        labelTunjanganTransportasi5 = new javax.swing.JLabel();
        comboBulan = new javax.swing.JComboBox<>();
        jPanel21 = new javax.swing.JPanel();
        labelTunjanganTransportasi6 = new javax.swing.JLabel();
        inputTahun = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(860, 1000));

        title.setText("Data Gaji Bersih");

        jPanel1.setMaximumSize(new java.awt.Dimension(830, 384));
        jPanel1.setMinimumSize(new java.awt.Dimension(830, 384));
        jPanel1.setPreferredSize(new java.awt.Dimension(830, 384));

        jPanel3.setLayout(new java.awt.GridLayout(1, 4, 40, 0));

        jPanel7.setPreferredSize(new java.awt.Dimension(100, 55));
        jPanel7.setLayout(new java.awt.BorderLayout(0, 10));

        labelGPokok1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelGPokok1.setText("ID");
        jPanel7.add(labelGPokok1, java.awt.BorderLayout.CENTER);

        inputId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputIdActionPerformed(evt);
            }
        });
        jPanel7.add(inputId, java.awt.BorderLayout.PAGE_END);

        jPanel3.add(jPanel7);
        jPanel7.getAccessibleContext().setAccessibleName("");

        jPanel10.setLayout(new java.awt.BorderLayout(0, 10));

        labelGPokok2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelGPokok2.setText("ID Gaji Kotor");
        jPanel10.add(labelGPokok2, java.awt.BorderLayout.CENTER);

        inputGajiKotorId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputGajiKotorIdActionPerformed(evt);
            }
        });
        jPanel10.add(inputGajiKotorId, java.awt.BorderLayout.PAGE_END);

        jPanel3.add(jPanel10);

        jPanel6.setLayout(new java.awt.BorderLayout(0, 10));

        labelGPokok3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelGPokok3.setText("Total Gaji Pokok");
        jPanel6.add(labelGPokok3, java.awt.BorderLayout.CENTER);

        inputGPokok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputGPokokActionPerformed(evt);
            }
        });
        jPanel6.add(inputGPokok, java.awt.BorderLayout.PAGE_END);

        jPanel3.add(jPanel6);

        jPanel11.setMinimumSize(new java.awt.Dimension(565, 55));
        jPanel11.setName(""); // NOI18N
        jPanel11.setPreferredSize(new java.awt.Dimension(565, 55));
        jPanel11.setRequestFocusEnabled(false);
        jPanel11.setVerifyInputWhenFocusTarget(false);
        jPanel11.setLayout(new java.awt.BorderLayout(0, 10));

        labelGolongan3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelGolongan3.setText("Nama Karyawan");
        jPanel11.add(labelGolongan3, java.awt.BorderLayout.CENTER);

        comboKaryawan.setToolTipText("");
        comboKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboKaryawanActionPerformed(evt);
            }
        });
        jPanel11.add(comboKaryawan, java.awt.BorderLayout.PAGE_END);

        jPanel3.add(jPanel11);

        jPanel5.setLayout(new java.awt.GridLayout(1, 0, 30, 0));

        jPanel4.setLayout(new java.awt.BorderLayout(0, 10));

        labelGPokok.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelGPokok.setText("Total Gaji Kotor");
        jPanel4.add(labelGPokok, java.awt.BorderLayout.CENTER);

        inputGKotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputGKotorActionPerformed(evt);
            }
        });
        jPanel4.add(inputGKotor, java.awt.BorderLayout.PAGE_END);

        jPanel5.add(jPanel4);

        jPanel15.setMaximumSize(new java.awt.Dimension(110, 55));
        jPanel15.setPreferredSize(new java.awt.Dimension(110, 55));
        jPanel15.setLayout(new java.awt.BorderLayout(0, 10));

        labelTunjanganJabatan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTunjanganJabatan.setText("Potongan Absen");
        jPanel15.add(labelTunjanganJabatan, java.awt.BorderLayout.CENTER);

        inputPotonganAbsen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPotonganAbsenActionPerformed(evt);
            }
        });
        jPanel15.add(inputPotonganAbsen, java.awt.BorderLayout.PAGE_END);

        jPanel5.add(jPanel15);

        jPanel19.setMaximumSize(new java.awt.Dimension(110, 55));
        jPanel19.setPreferredSize(new java.awt.Dimension(110, 55));
        jPanel19.setLayout(new java.awt.BorderLayout(0, 10));

        labelTunjanganLembur.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTunjanganLembur.setText("Jumlah Absen");
        jPanel19.add(labelTunjanganLembur, java.awt.BorderLayout.CENTER);

        inputJumlahAbsen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputJumlahAbsenActionPerformed(evt);
            }
        });
        jPanel19.add(inputJumlahAbsen, java.awt.BorderLayout.PAGE_END);
        inputJumlahAbsen.getAccessibleContext().setAccessibleName("");

        jPanel5.add(jPanel19);

        jPanel20.setMaximumSize(new java.awt.Dimension(30, 55));
        jPanel20.setLayout(new java.awt.BorderLayout(0, 10));

        labelTunjanganLembur3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTunjanganLembur3.setText("JHT Karyawan");
        jPanel20.add(labelTunjanganLembur3, java.awt.BorderLayout.CENTER);

        inputJht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputJhtActionPerformed(evt);
            }
        });
        jPanel20.add(inputJht, java.awt.BorderLayout.PAGE_END);

        jPanel5.add(jPanel20);
        jPanel20.getAccessibleContext().setAccessibleDescription("");

        jPanel8.setLayout(new java.awt.GridLayout(1, 0, 40, 0));

        jPanel18.setName(""); // NOI18N
        jPanel18.setLayout(new java.awt.BorderLayout(0, 10));

        labelTunjanganTransportasi5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTunjanganTransportasi5.setText("Bulan");
        jPanel18.add(labelTunjanganTransportasi5, java.awt.BorderLayout.CENTER);

        comboBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        comboBulan.setToolTipText("");
        comboBulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBulanActionPerformed(evt);
            }
        });
        jPanel18.add(comboBulan, java.awt.BorderLayout.PAGE_END);

        jPanel8.add(jPanel18);

        jPanel21.setName(""); // NOI18N
        jPanel21.setPreferredSize(new java.awt.Dimension(125, 55));
        jPanel21.setLayout(new java.awt.BorderLayout(0, 10));

        labelTunjanganTransportasi6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTunjanganTransportasi6.setText("Tahun");
        jPanel21.add(labelTunjanganTransportasi6, java.awt.BorderLayout.CENTER);

        inputTahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTahunActionPerformed(evt);
            }
        });
        jPanel21.add(inputTahun, java.awt.BorderLayout.PAGE_END);

        jPanel8.add(jPanel21);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 974, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 974, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        save.setText("Save");
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMouseClicked(evt);
            }
        });

        edit.setText("Edit");
        edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        delete.setText("Delete");
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(save)
                        .addGap(0, 0, 0)
                        .addComponent(edit)
                        .addGap(18, 18, 18)
                        .addComponent(delete))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 974, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(title)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save)
                    .addComponent(edit)
                    .addComponent(delete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editActionPerformed

    private void saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseClicked
        if(inputGPokok.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Pilih ID terlebih dahulu!");
            return;
        }
        
        Long gaji_kotor_id = Long.parseLong(
            inputGajiKotorId.getText()
                .toString()
                .replace("#", "")
        );
        int g_pokok = Integer.parseInt(inputGPokok.getText());
        int total_kotor = Integer.parseInt(inputGKotor.getText());
        KaryawanModel karyawan = (KaryawanModel) comboKaryawan.getSelectedItem();        
        
        int p_absen = Integer.parseInt(inputPotonganAbsen.getText());
        String jumlah_absen = inputJumlahAbsen.getText();
        double jht = Double.parseDouble(inputJht.getText());
        
        String bulan = comboBulan.getSelectedItem().toString();
        int tahun = Integer.parseInt(inputTahun.getText());

        
        int p_jabatan = 0;
        int jumlah_absen_final;
        int total_bersih = 0;
        try {

            jumlah_absen_final = (int) 
                Math.round(total_kotor * 5 / 100);
            jumlah_absen_final = Integer.parseInt(jumlah_absen);
            total_bersih = (int) Math.round(
                    total_kotor - jumlah_absen_final
                    - (jumlah_absen_final * p_absen)
                    - (g_pokok * jht / 100));
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "ID Gaji Kotor & Jumlah Absen harus angka");
            return;
        }        

        GajiBersihModel model = new GajiBersihModel();
        model.setKaryawanId(karyawan.getId());        
        model.setGajiKotorId(gaji_kotor_id);
        model.setPotonganJabatan(p_jabatan);
        model.setPotonganAbsen(p_absen);
        model.setJumlahAbsen(jumlah_absen_final);
        model.setJht(jht);
        model.setTotal(total_bersih);

        model.setBulan(bulan);
        model.setTahun(tahun);

        GajiBersihDao gajiBersihDao = new GajiBersihDao();

        if (gajiBersihDao.saveData(model)) {
            panel.loadTable("");
            dispose();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
        } else {
            JOptionPane.showMessageDialog(null, "Gagal menyimpan data");
        }
    }//GEN-LAST:event_saveMouseClicked

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        Long id = Long.parseLong(
            inputId.getText()
                .toString()
                .replace("#", "")
        );

        GajiBersihDao gajiBersihDao = new GajiBersihDao();

        if (gajiBersihDao.deleteData(id)) {
            panel.loadTable("");
            dispose();
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
        } else {
            JOptionPane.showMessageDialog(null, "Gagal menghapus data");
        }
    }//GEN-LAST:event_deleteMouseClicked

    private void editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseClicked
        Long id = Long.parseLong(
            inputId.getText()
                .toString()
                .replace("#", "")
        );
        

        Long gaji_kotor_id = Long.parseLong(
            inputGajiKotorId.getText()
                .toString()
                .replace("#", "")
        );
        int g_pokok = Integer.parseInt(inputGPokok.getText());
        int total_kotor = Integer.parseInt(inputGKotor.getText());
        KaryawanModel karyawan = (KaryawanModel) comboKaryawan.getSelectedItem();        
        
        int p_absen = Integer.parseInt(inputPotonganAbsen.getText());
        String jumlah_absen = inputJumlahAbsen.getText();
        double jht = Double.parseDouble(inputJht.getText());
        
        String bulan = comboBulan.getSelectedItem().toString();
        int tahun = Integer.parseInt(inputTahun.getText());

        
        int p_jabatan = 0;
        int jumlah_absen_final;
        int total_bersih = 0;
          
        try {

            jumlah_absen_final = (int) 
                Math.round(total_kotor * 5 / 100);
            jumlah_absen_final = Integer.parseInt(jumlah_absen);
            total_bersih = (int) Math.round(
                    total_kotor - jumlah_absen_final
                    - (jumlah_absen_final * p_absen)
                    - (g_pokok * jht / 100));
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "ID Gaji Kotor & Jumlah Absen harus angka");
            return;
        }   

        GajiBersihModel model = new GajiBersihModel();
        model.setId(id);        
        model.setJumlahAbsen(jumlah_absen_final);
        model.setTotal(total_bersih);

        GajiBersihDao gajiBersihDao = new GajiBersihDao();

        if (gajiBersihDao.editData(model)) {
            panel.loadTable("");
            dispose();
            JOptionPane.showMessageDialog(null, "Data berhasil diedit");
        } else {
            JOptionPane.showMessageDialog(null, "Gagal mengedit data");
        }
    }//GEN-LAST:event_editMouseClicked

    private void inputJumlahAbsenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputJumlahAbsenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputJumlahAbsenActionPerformed

    private void inputGKotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputGKotorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputGKotorActionPerformed

    private void comboKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboKaryawanActionPerformed

    }//GEN-LAST:event_comboKaryawanActionPerformed

    private void inputIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputIdActionPerformed

    private void inputJhtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputJhtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputJhtActionPerformed

    private void inputTahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTahunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTahunActionPerformed

    private void comboBulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBulanActionPerformed

    }//GEN-LAST:event_comboBulanActionPerformed

    private void inputGajiKotorIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputGajiKotorIdActionPerformed
        Long gajiKotorId = Long.parseLong(
            inputGajiKotorId.getText()
                .toString()
                .replace("#", "")
        );
        GajiKotorDao gajiKotorDao = new GajiKotorDao();
        GajiKotorModel gajiKotorModel = gajiKotorDao.getById(gajiKotorId);
        
        if (gajiKotorModel == null) {
            return;
        }

        inputGPokok.setText("" + gajiKotorModel.getGajiPokok());
        inputGKotor.setText("" + gajiKotorModel.getTotal());
        comboBulan.setSelectedItem(gajiKotorModel.getBulan());
        inputTahun.setText("" + gajiKotorModel.getTahun());
        
        
        inputPotonganAbsen.setText("" 
                + gajiKotorModel.getKaryawanModel().getPotonganAbsen());

        KaryawanModel karyawanTarget = gajiKotorModel.getKaryawanModel();
        loadComboKaryawan();
        for (int i = 0; i < comboKaryawan.getItemCount(); i++) {
            KaryawanModel item = comboKaryawan.getItemAt(i);

            if (item.getId() == karyawanTarget.getId()) {
                comboKaryawan.setSelectedIndex(i);
                break;
            }
        }
        
        BpjsDao bpjsDao = new BpjsDao();
        BpjsModel bpjsModel = bpjsDao.getDataFirst();
        inputJht.setText("" + bpjsModel.getJhtK());
    
    }//GEN-LAST:event_inputGajiKotorIdActionPerformed

    private void inputGPokokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputGPokokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputGPokokActionPerformed

    private void inputPotonganAbsenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPotonganAbsenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPotonganAbsenActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GajiBersihDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GajiBersihDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GajiBersihDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GajiBersihDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        GajiBersih panel = new GajiBersih();

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GajiBersihDialog dialog = new GajiBersihDialog(new javax.swing.JFrame(), true, "", 0L, panel);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBulan;
    private javax.swing.JComboBox<KaryawanModel> comboKaryawan;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JTextField inputGKotor;
    private javax.swing.JTextField inputGPokok;
    private javax.swing.JTextField inputGajiKotorId;
    private javax.swing.JTextField inputId;
    private javax.swing.JTextField inputJht;
    private javax.swing.JTextField inputJumlahAbsen;
    private javax.swing.JTextField inputPotonganAbsen;
    private javax.swing.JTextField inputTahun;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel labelGPokok;
    private javax.swing.JLabel labelGPokok1;
    private javax.swing.JLabel labelGPokok2;
    private javax.swing.JLabel labelGPokok3;
    private javax.swing.JLabel labelGolongan3;
    private javax.swing.JLabel labelTunjanganJabatan;
    private javax.swing.JLabel labelTunjanganLembur;
    private javax.swing.JLabel labelTunjanganLembur3;
    private javax.swing.JLabel labelTunjanganTransportasi5;
    private javax.swing.JLabel labelTunjanganTransportasi6;
    private javax.swing.JButton save;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
