/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penggajian.dialog;

import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import penggajian.dao.BpjsDao;
import penggajian.dao.GajiKotorDao;
import penggajian.dao.JabatanDao;
import penggajian.dao.KaryawanDao;
import penggajian.dao.TerDao;
import penggajian.helper.BaseSetting;
import penggajian.model.BpjsModel;
import penggajian.model.GajiKotorModel;
import penggajian.model.JabatanModel;
import penggajian.model.KaryawanModel;
import penggajian.model.TerModel;
import penggajian.page.dashboard.GajiKotor;

/**
 *
 * @author Dion
 */
public class GajiKotorDialog extends javax.swing.JDialog {
    private GajiKotor panel;
    /**
     * Creates new form JabatanDialog
     */
    public GajiKotorDialog(java.awt.Frame parent, boolean modal, String typeDialog, Long id, GajiKotor panel) {
        super(parent, modal);
        this.panel = panel;
        initComponents();
        
        BaseSetting.setTitlePanel(title);
        title.setText(
            typeDialog + " " + title.getText()
        );
        
        BaseSetting.setInput(inputId);
        inputId.setEditable(false);
        BaseSetting.setCombo(comboKaryawan);
        loadComboKaryawan();
        BaseSetting.setInput(inputGPokok);
        inputGPokok.setEditable(false);
        
        BaseSetting.setInput(inputTunjanganTransportasi);
        inputTunjanganTransportasi.setEditable(false);
        BaseSetting.setInput(inputTunjanganMakan);
        inputTunjanganMakan.setEditable(false);
        BaseSetting.setInput(inputTunjanganJabatan);
        inputTunjanganJabatan.setEditable(false);
        BaseSetting.setInput(inputTunjanganLembur);
        inputTunjanganLembur.setEditable(false);
        BaseSetting.setInput(inputJumlahLembur);
        BaseSetting.setInput(inputJkk);
        inputJkk.setEditable(false);
        BaseSetting.setInput(inputJkm);
        inputJkm.setEditable(false);
        BaseSetting.setInput(inputJht);
        inputJht.setEditable(false);
 
        BaseSetting.setCombo(comboGolonganTer);
        comboGolonganTer.setEnabled(false);
        BaseSetting.setCombo(comboBulan);
        BaseSetting.setInput(inputTahun);

        
        
        BaseSetting.setButton(save);
        BaseSetting.setButton(edit);
        BaseSetting.setButton(delete);

        if(typeDialog.equals("Edit")){
            save.setVisible(false);
            edit.setVisible(true);
            delete.setVisible(true);
            
            GajiKotorDao gajiKotorDao = new GajiKotorDao();
            GajiKotorModel gaji = gajiKotorDao.getById(id);
            inputId.setText("#" + gaji.getId());
            inputGPokok.setText("" + gaji.getGajiPokok());
            comboKaryawan.setEnabled(false);
            inputTunjanganMakan.setText("" + gaji.getTunjanganMakan());
            inputTunjanganTransportasi.setText("" + gaji.getTunjanganTransportasi());
            inputTunjanganJabatan.setText("" + gaji.getTunjanganJabatan());
            inputTunjanganLembur.setText("" + gaji.getTunjanganLembur());
            inputJumlahLembur.setText("" + gaji.getJumlahLembur());
            
            inputJht.setText("" + gaji.getJhtPerusahaan());
            inputJkm.setText("" + gaji.getJkm());
            inputJkk.setText("" + gaji.getJkk());
            
            comboGolonganTer.setSelectedItem(gaji.getGolonganTer());
            comboGolonganTer.setEnabled(false);
            comboBulan.setSelectedItem(gaji.getBulan());
            inputTahun.setText("" + gaji.getTahun());

            KaryawanModel karyawanTarget = gaji.getKaryawanModel();
            for (int i = 0; i < comboKaryawan.getItemCount(); i++) {
                KaryawanModel item = comboKaryawan.getItemAt(i);

                if (item.getId() == karyawanTarget.getId()) {
                    comboKaryawan.setSelectedIndex(i);
                    break;
                }
            }
            

        }else{
            save.setVisible(true);
            edit.setVisible(false);
            delete.setVisible(false);
        }
    }
    
    private void loadComboKaryawan() {
        comboKaryawan.removeAllItems();

        try {
            KaryawanDao karyawanDao = new KaryawanDao(); 
            List<KaryawanModel> listKaryawan = karyawanDao.getAllData("", false); 

            for (KaryawanModel k : listKaryawan) {
                comboKaryawan.addItem(k); 
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        labelGPokok1 = new javax.swing.JLabel();
        inputId = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        labelGPokok = new javax.swing.JLabel();
        inputGPokok = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        labelGolongan3 = new javax.swing.JLabel();
        comboKaryawan = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        labelTunjanganMakan = new javax.swing.JLabel();
        inputTunjanganMakan = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        labelTunjanganTransportasi = new javax.swing.JLabel();
        inputTunjanganTransportasi = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        labelTunjanganJabatan = new javax.swing.JLabel();
        inputTunjanganJabatan = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        labelTunjanganLembur = new javax.swing.JLabel();
        inputTunjanganLembur = new javax.swing.JTextField();
        jPanel20 = new javax.swing.JPanel();
        labelTunjanganLembur3 = new javax.swing.JLabel();
        inputJumlahLembur = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        labelTunjanganTransportasi3 = new javax.swing.JLabel();
        inputJht = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        labelTunjanganTransportasi2 = new javax.swing.JLabel();
        inputJkm = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        labelTunjanganTransportasi1 = new javax.swing.JLabel();
        inputJkk = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        labelGolongan4 = new javax.swing.JLabel();
        comboGolonganTer = new javax.swing.JComboBox<>();
        jPanel18 = new javax.swing.JPanel();
        labelTunjanganTransportasi5 = new javax.swing.JLabel();
        comboBulan = new javax.swing.JComboBox<>();
        jPanel21 = new javax.swing.JPanel();
        labelTunjanganTransportasi6 = new javax.swing.JLabel();
        inputTahun = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        labelTunjanganTransportasi7 = new javax.swing.JLabel();
        inputTahun1 = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        save = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(860, 1000));

        title.setText("Data Gaji Kotor");

        jPanel1.setMaximumSize(new java.awt.Dimension(830, 384));
        jPanel1.setMinimumSize(new java.awt.Dimension(830, 384));

        jPanel3.setLayout(new java.awt.GridLayout(1, 0, 40, 0));

        labelGPokok1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelGPokok1.setText("ID");

        inputId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inputId)
            .addComponent(labelGPokok1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(labelGPokok1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(jPanel7);
        jPanel7.getAccessibleContext().setAccessibleName("");

        labelGPokok.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelGPokok.setText("Gaji Pokok");

        inputGPokok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputGPokokActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inputGPokok)
            .addComponent(labelGPokok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(labelGPokok)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputGPokok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(jPanel4);

        labelGolongan3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelGolongan3.setText("Nama Karyawan");

        comboKaryawan.setToolTipText("");
        comboKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboKaryawanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelGolongan3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(comboKaryawan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(labelGolongan3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel11);

        jPanel5.setLayout(new java.awt.GridLayout(1, 0, 40, 0));

        jPanel14.setMaximumSize(new java.awt.Dimension(120, 55));
        jPanel14.setPreferredSize(new java.awt.Dimension(120, 55));
        jPanel14.setLayout(new java.awt.BorderLayout(0, 10));

        labelTunjanganMakan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTunjanganMakan.setText("T. Makan");
        jPanel14.add(labelTunjanganMakan, java.awt.BorderLayout.LINE_START);

        inputTunjanganMakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTunjanganMakanActionPerformed(evt);
            }
        });
        jPanel14.add(inputTunjanganMakan, java.awt.BorderLayout.PAGE_END);

        jPanel5.add(jPanel14);
        jPanel14.getAccessibleContext().setAccessibleName("");

        jPanel10.setMaximumSize(new java.awt.Dimension(18, 32767));
        jPanel10.setName(""); // NOI18N
        jPanel10.setPreferredSize(new java.awt.Dimension(18, 55));
        jPanel10.setLayout(new java.awt.BorderLayout(0, 10));

        labelTunjanganTransportasi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTunjanganTransportasi.setText("T. Transportasi");
        jPanel10.add(labelTunjanganTransportasi, java.awt.BorderLayout.CENTER);

        inputTunjanganTransportasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTunjanganTransportasiActionPerformed(evt);
            }
        });
        jPanel10.add(inputTunjanganTransportasi, java.awt.BorderLayout.PAGE_END);

        jPanel5.add(jPanel10);

        jPanel15.setMaximumSize(new java.awt.Dimension(110, 55));
        jPanel15.setPreferredSize(new java.awt.Dimension(110, 55));
        jPanel15.setLayout(new java.awt.BorderLayout(0, 10));

        labelTunjanganJabatan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTunjanganJabatan.setText("T. Jabatan");
        jPanel15.add(labelTunjanganJabatan, java.awt.BorderLayout.CENTER);

        inputTunjanganJabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTunjanganJabatanActionPerformed(evt);
            }
        });
        jPanel15.add(inputTunjanganJabatan, java.awt.BorderLayout.PAGE_END);

        jPanel5.add(jPanel15);

        jPanel19.setMaximumSize(new java.awt.Dimension(110, 55));
        jPanel19.setPreferredSize(new java.awt.Dimension(110, 55));
        jPanel19.setLayout(new java.awt.BorderLayout(0, 10));

        labelTunjanganLembur.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTunjanganLembur.setText("T. Lembur");
        jPanel19.add(labelTunjanganLembur, java.awt.BorderLayout.CENTER);

        inputTunjanganLembur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTunjanganLemburActionPerformed(evt);
            }
        });
        jPanel19.add(inputTunjanganLembur, java.awt.BorderLayout.PAGE_END);
        inputTunjanganLembur.getAccessibleContext().setAccessibleName("");

        jPanel5.add(jPanel19);

        jPanel20.setMaximumSize(new java.awt.Dimension(30, 55));
        jPanel20.setLayout(new java.awt.BorderLayout(0, 10));

        labelTunjanganLembur3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTunjanganLembur3.setText("Jam Lembur");
        jPanel20.add(labelTunjanganLembur3, java.awt.BorderLayout.CENTER);

        inputJumlahLembur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputJumlahLemburActionPerformed(evt);
            }
        });
        jPanel20.add(inputJumlahLembur, java.awt.BorderLayout.PAGE_END);

        jPanel5.add(jPanel20);
        jPanel20.getAccessibleContext().setAccessibleDescription("");

        jPanel6.setLayout(new java.awt.GridLayout(1, 0, 40, 0));

        jPanel16.setName(""); // NOI18N

        labelTunjanganTransportasi3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTunjanganTransportasi3.setText("JHT Perusahaan");

        inputJht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputJhtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTunjanganTransportasi3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(inputJht)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addComponent(labelTunjanganTransportasi3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputJht, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel6.add(jPanel16);

        jPanel13.setName(""); // NOI18N

        labelTunjanganTransportasi2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTunjanganTransportasi2.setText("JKM");

        inputJkm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputJkmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTunjanganTransportasi2, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
            .addComponent(inputJkm)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(labelTunjanganTransportasi2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputJkm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanel6.add(jPanel13);

        jPanel12.setName(""); // NOI18N
        jPanel12.setPreferredSize(new java.awt.Dimension(125, 55));

        labelTunjanganTransportasi1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTunjanganTransportasi1.setText("JKK");

        inputJkk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputJkkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTunjanganTransportasi1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(inputJkk)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(labelTunjanganTransportasi1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputJkk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel6.add(jPanel12);

        jPanel8.setLayout(new java.awt.GridLayout(1, 0, 40, 0));

        labelGolongan4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelGolongan4.setText("Golongan Ter");

        comboGolonganTer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));
        comboGolonganTer.setToolTipText("");
        comboGolonganTer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboGolonganTerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelGolongan4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(comboGolonganTer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(labelGolongan4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboGolonganTer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel8.add(jPanel22);

        jPanel18.setName(""); // NOI18N

        labelTunjanganTransportasi5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTunjanganTransportasi5.setText("Bulan");

        comboBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        comboBulan.setToolTipText("");
        comboBulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBulanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTunjanganTransportasi5, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
            .addComponent(comboBulan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addComponent(labelTunjanganTransportasi5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(comboBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel8.add(jPanel18);

        jPanel21.setName(""); // NOI18N
        jPanel21.setPreferredSize(new java.awt.Dimension(125, 55));

        labelTunjanganTransportasi6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTunjanganTransportasi6.setText("Tahun");

        inputTahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTahunActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel23.setName(""); // NOI18N
        jPanel23.setPreferredSize(new java.awt.Dimension(125, 55));

        labelTunjanganTransportasi7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTunjanganTransportasi7.setText("Tahun");

        inputTahun1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTahun1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTunjanganTransportasi7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(inputTahun1)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 61, Short.MAX_VALUE))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addComponent(labelTunjanganTransportasi7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputTahun1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTunjanganTransportasi6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(inputTahun)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel21Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addComponent(labelTunjanganTransportasi6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel21Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel8.add(jPanel21);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        save.setText("Save");
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMouseClicked(evt);
            }
        });

        edit.setText("Edit");
        edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        delete.setText("Delete");
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(save)
                        .addGap(0, 0, 0)
                        .addComponent(edit)
                        .addGap(18, 18, 18)
                        .addComponent(delete))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(title)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save)
                    .addComponent(edit)
                    .addComponent(delete))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editActionPerformed

    private void saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseClicked
        String g_pokok = inputGPokok.getText();
        KaryawanModel karyawan = (KaryawanModel) comboKaryawan.getSelectedItem();        
        
        String t_makan = inputTunjanganMakan.getText();
        String t_transportasi = inputTunjanganTransportasi.getText();
        String t_jabatan = inputTunjanganJabatan.getText();
        String t_lembur = inputTunjanganLembur.getText();
        String jumlah_lembur = inputJumlahLembur.getText();

        double jht = Double.parseDouble(inputJht.getText());
        double jkm = Double.parseDouble(inputJkm.getText());
        double jkk = Double.parseDouble(inputJkk.getText());
        
        String golongan = comboGolonganTer.getSelectedItem().toString();
        String bulan = comboBulan.getSelectedItem().toString();
        String tahun = inputTahun.getText();

        int jumlah_lembur_final;
        int total_1;
        int total_2;
        int pph_21;
        Double tarifTer;
        int total_kotor = 0;
        int tahun_final;
        try {

            jumlah_lembur_final = Integer.parseInt(jumlah_lembur);
            total_1 = Integer.parseInt(g_pokok)
                    + Integer.parseInt(t_makan) 
                    + Integer.parseInt(t_transportasi) 
                    + Integer.parseInt(t_jabatan) 
                    + (Integer.parseInt(t_lembur) 
                    * jumlah_lembur_final);
            
            double maxGaji = 12000000;
            double dasarHitung = Math.min(total_1, maxGaji);

            total_2 = (int) Math.round(
                    total_1
                    + (dasarHitung * jht / 100)
                    + (dasarHitung * jkk / 100)
                    + (dasarHitung * jkm / 100));
            
            TerDao terDao = new TerDao();
            TerModel terModel = terDao.getByMinMax(total_2);
            
            tarifTer = (terModel != null) ? terModel.getTarif() : null;
            tarifTer = tarifTer != null ? (tarifTer / 100) : 0;
            
            pph_21 = (int) Math.round(tarifTer * total_2);
            total_kotor = pph_21 + total_2;
            
            
            tahun_final = Integer.parseInt(tahun);
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Jam Lembur, & Tahun harus angka");
            return;
        }
        
        if(total_kotor == 0){
            JOptionPane.showMessageDialog(null, "Data tidak lengkap!");
            return;
        }

        GajiKotorModel model = new GajiKotorModel();
        model.setGajiPokok(Integer.parseInt(g_pokok));
        model.setKaryawanId(karyawan.getId());
        
        model.setTunjanganMakan(Integer.parseInt(t_makan));
        model.setTunjanganTransportasi(Integer.parseInt(t_transportasi));
        model.setTunjanganJabatan(Integer.parseInt(t_jabatan));
        model.setTunjanganLembur(Integer.parseInt(t_lembur));
        model.setJumlahLembur(jumlah_lembur_final);
        model.setTotal1(total_1);
        
        model.setJkk(jkk);
        model.setJhtPerusahaan(jht);
        model.setJkm(jkm);
        model.setTotal2(total_2);
        
        model.setGolonganTer(golongan);
        model.setTarifTer(tarifTer);
        model.setTotalTer(pph_21);
        model.setTotal(total_kotor);

        model.setBulan(bulan);
        model.setTahun(tahun_final);

        GajiKotorDao gajiKotorDao = new GajiKotorDao();

        if (gajiKotorDao.saveData(model)) {
            panel.loadTable("");
            dispose();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
        } else {
            JOptionPane.showMessageDialog(null, "Gagal menyimpan data");
        }
    }//GEN-LAST:event_saveMouseClicked

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        Long id = Long.parseLong(
            inputId.getText()
                .toString()
                .replace("#", "")
        );

        GajiKotorDao gajiKotorDao = new GajiKotorDao();

        if (gajiKotorDao.deleteData(id)) {
            panel.loadTable("");
            dispose();
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
        } else {
            JOptionPane.showMessageDialog(null, "Gagal menghapus data");
        }
    }//GEN-LAST:event_deleteMouseClicked

    private void editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseClicked
        Long id = Long.parseLong(
            inputId.getText()
                .toString()
                .replace("#", "")
        );
        
        String g_pokok = inputGPokok.getText();
        KaryawanModel karyawan = (KaryawanModel) comboKaryawan.getSelectedItem();        
        
        String t_makan = inputTunjanganMakan.getText();
        String t_transportasi = inputTunjanganTransportasi.getText();
        String t_jabatan = inputTunjanganJabatan.getText();
        String t_lembur = inputTunjanganLembur.getText();
        String jumlah_lembur = inputJumlahLembur.getText();

        double jht = Double.parseDouble(inputJht.getText());
        double jkm = Double.parseDouble(inputJkm.getText());
        double jkk = Double.parseDouble(inputJkk.getText());
        
        String golongan = comboGolonganTer.getSelectedItem().toString();
        String bulan = comboBulan.getSelectedItem().toString();
        String tahun = inputTahun.getText();
        
        int jumlah_lembur_final;
        int total_1;
        int total_2;
        int pph_21;
        Double tarifTer;
        int total_kotor = 0;
        int tahun_final;
        try {

            jumlah_lembur_final = Integer.parseInt(jumlah_lembur);
            total_1 = Integer.parseInt(g_pokok)
                    + Integer.parseInt(t_makan) 
                    + Integer.parseInt(t_transportasi) 
                    + Integer.parseInt(t_jabatan) 
                    + (Integer.parseInt(t_lembur) 
                    * jumlah_lembur_final);
            
            double maxGaji = 12000000;
            double dasarHitung = Math.min(total_1, maxGaji);

            total_2 = (int) Math.round(
                    total_1
                    + (dasarHitung * jht / 100)
                    + (dasarHitung * jkk / 100)
                    + (dasarHitung * jkm / 100));
            
            TerDao terDao = new TerDao();
            TerModel terModel = terDao.getByMinMax(total_2);
            
            tarifTer = (terModel != null) ? terModel.getTarif() : null;
            tarifTer = tarifTer != null ? (tarifTer / 100) : 0;
            
            pph_21 = (int) Math.round(tarifTer * total_2);
            total_kotor = pph_21 + total_2;
            
            
            tahun_final = Integer.parseInt(tahun);
                        
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Jam Lembur, & Tahun harus angka");
            return;
        }
        
        if(total_kotor == 0){
            JOptionPane.showMessageDialog(null, "Data tidak lengkap!");
            return;
        }


        GajiKotorModel model = new GajiKotorModel();
        model.setId(id);
        model.setGajiPokok(Integer.parseInt(g_pokok));
        model.setKaryawanId(karyawan.getId());
        
        model.setTunjanganMakan(Integer.parseInt(t_makan));
        model.setTunjanganTransportasi(Integer.parseInt(t_transportasi));
        model.setTunjanganJabatan(Integer.parseInt(t_jabatan));
        model.setTunjanganLembur(Integer.parseInt(t_lembur));
        model.setJumlahLembur(jumlah_lembur_final);
        model.setTotal1(total_1);
        
        model.setJkk(jkk);
        model.setJhtPerusahaan(jht);
        model.setJkm(jkm);
        model.setTotal2(total_2);
        
        model.setGolonganTer(golongan);
        model.setTarifTer(tarifTer);
        model.setTotalTer(pph_21);
        model.setTotal(total_kotor);

        model.setBulan(bulan);
        model.setTahun(tahun_final);

        GajiKotorDao gajiKotorDao = new GajiKotorDao();

        if (gajiKotorDao.editData(model)) {
            panel.loadTable("");
            dispose();
            JOptionPane.showMessageDialog(null, "Data berhasil diedit");
        } else {
            JOptionPane.showMessageDialog(null, "Gagal mengedit data");
        }
    }//GEN-LAST:event_editMouseClicked

    private void inputJumlahLemburActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputJumlahLemburActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputJumlahLemburActionPerformed

    private void inputTunjanganLemburActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTunjanganLemburActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTunjanganLemburActionPerformed

    private void inputTunjanganJabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTunjanganJabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTunjanganJabatanActionPerformed

    private void inputTunjanganMakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTunjanganMakanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTunjanganMakanActionPerformed

    private void inputTunjanganTransportasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTunjanganTransportasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTunjanganTransportasiActionPerformed

    private void inputGPokokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputGPokokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputGPokokActionPerformed

    private void comboKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboKaryawanActionPerformed
        KaryawanDao karyawanDao = new KaryawanDao();
        Long karyawanId = ((KaryawanModel) comboKaryawan.getSelectedItem()).getId();
        
        KaryawanModel karyawan = karyawanDao.getById(karyawanId);
        
        BpjsDao bpjsDao = new BpjsDao();
        BpjsModel bpjsModel = bpjsDao.getDataFirst();
       
        
        inputGPokok.setText("" + karyawan.getGajiPokok());
        inputTunjanganMakan.setText("" + karyawan.getTunjanganMakan());
        inputTunjanganTransportasi.setText("" + karyawan.getTunjanganTransportasi());
        
        inputTunjanganJabatan.setText("" + karyawan.getJabatanModel().getTunjangan());
        inputTunjanganLembur.setText("" + karyawan.getTunjanganLembur());
        
        inputJht.setText("" + bpjsModel.getJhtP());
        inputJkm.setText("" + bpjsModel.getJkm());
        inputJkk.setText("" + bpjsModel.getJkk());
        
        comboGolonganTer.setSelectedItem(karyawan.getGolonganTer());
    }//GEN-LAST:event_comboKaryawanActionPerformed

    private void inputIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputIdActionPerformed

    private void inputJkkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputJkkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputJkkActionPerformed

    private void inputJkmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputJkmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputJkmActionPerformed

    private void inputJhtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputJhtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputJhtActionPerformed

    private void inputTahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTahunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTahunActionPerformed

    private void comboGolonganTerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboGolonganTerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboGolonganTerActionPerformed

    private void comboBulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBulanActionPerformed

    }//GEN-LAST:event_comboBulanActionPerformed

    private void inputTahun1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTahun1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTahun1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GajiKotorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GajiKotorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GajiKotorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GajiKotorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        GajiKotor panel = new GajiKotor();

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GajiKotorDialog dialog = new GajiKotorDialog(new javax.swing.JFrame(), true, "", 0L, panel);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBulan;
    private javax.swing.JComboBox<String> comboGolonganTer;
    private javax.swing.JComboBox<KaryawanModel> comboKaryawan;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JTextField inputGPokok;
    private javax.swing.JTextField inputId;
    private javax.swing.JTextField inputJht;
    private javax.swing.JTextField inputJkk;
    private javax.swing.JTextField inputJkm;
    private javax.swing.JTextField inputJumlahLembur;
    private javax.swing.JTextField inputTahun;
    private javax.swing.JTextField inputTahun1;
    private javax.swing.JTextField inputTunjanganJabatan;
    private javax.swing.JTextField inputTunjanganLembur;
    private javax.swing.JTextField inputTunjanganMakan;
    private javax.swing.JTextField inputTunjanganTransportasi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel labelGPokok;
    private javax.swing.JLabel labelGPokok1;
    private javax.swing.JLabel labelGolongan3;
    private javax.swing.JLabel labelGolongan4;
    private javax.swing.JLabel labelTunjanganJabatan;
    private javax.swing.JLabel labelTunjanganLembur;
    private javax.swing.JLabel labelTunjanganLembur3;
    private javax.swing.JLabel labelTunjanganMakan;
    private javax.swing.JLabel labelTunjanganTransportasi;
    private javax.swing.JLabel labelTunjanganTransportasi1;
    private javax.swing.JLabel labelTunjanganTransportasi2;
    private javax.swing.JLabel labelTunjanganTransportasi3;
    private javax.swing.JLabel labelTunjanganTransportasi5;
    private javax.swing.JLabel labelTunjanganTransportasi6;
    private javax.swing.JLabel labelTunjanganTransportasi7;
    private javax.swing.JButton save;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
