/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penggajian.dialog;

import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import penggajian.dao.JabatanDao;
import penggajian.dao.KaryawanDao;
import penggajian.helper.BaseSetting;
import penggajian.model.JabatanModel;
import penggajian.model.KaryawanModel;
import penggajian.page.dashboard.GajiKotor;

/**
 *
 * @author Dion
 */
public class GajiKotorDialog extends javax.swing.JDialog {
    private GajiKotor panel;
    /**
     * Creates new form JabatanDialog
     */
    public GajiKotorDialog(java.awt.Frame parent, boolean modal, String typeDialog, Long id, GajiKotor panel) {
        super(parent, modal);
        this.panel = panel;
        initComponents();
        
        BaseSetting.setTitlePanel(title);
        title.setText(
            typeDialog + " " + title.getText()
        );
        
        BaseSetting.setInput(inputId);
        inputId.setEditable(false);
        BaseSetting.setCombo(comboKaryawan);
        loadComboKaryawan();
        BaseSetting.setInput(inputGPokok);
        
        BaseSetting.setInput(inputTunjanganTransportasi);
        BaseSetting.setInput(inputTunjanganMakan);
        BaseSetting.setInput(inputTunjanganJabatan);
        BaseSetting.setInput(inputTunjanganLembur);
        BaseSetting.setInput(inputJumlahLembur);
        BaseSetting.setInput(inputJkk);
        inputJkk.setEditable(false);
        BaseSetting.setInput(inputJkm);
        inputJkm.setEditable(false);
        BaseSetting.setInput(inputJht);
        inputJht.setEditable(false);
        
        
        BaseSetting.setButton(save);
        BaseSetting.setButton(edit);
        BaseSetting.setButton(delete);

        if(typeDialog.equals("Edit")){
            save.setVisible(false);
            edit.setVisible(true);
            delete.setVisible(true);
            
            KaryawanDao karyawanDao = new KaryawanDao();

            KaryawanModel t = karyawanDao.getById(id);
            inputId.setText("#" + t.getId());
//            inputNama.setText(t.getNama());
            inputGPokok.setText("" + t.getGajiPokok());

            inputTunjanganTransportasi.setText("" + t.getTunjanganTransportasi());
            inputTunjanganMakan.setText("" + t.getTunjanganMakan());
            inputTunjanganJabatan.setText("" + t.getTunjanganLembur());
//            inputPotongaAbsen.setText("" + t.getPotonganAbsen());
//            comboGolongan.setSelectedItem(t.getGolonganTer());
                       
//            KaryawanModel target = t.getKaryawanModel();
//
//            for (int i = 0; i < comboKaryawan.getItemCount(); i++) {
//                KaryawanModel item = comboKaryawan.getItemAt(i);
//
//                if (item.getId() == target.getId()) {
//                    comboKaryawan.setSelectedIndex(i);
//                    break;
//                }
//            }


        }else{
            save.setVisible(true);
            edit.setVisible(false);
            delete.setVisible(false);
        }
    }
    
    private void loadComboKaryawan() {
        comboKaryawan.removeAllItems();

        try {
            KaryawanDao karyawanDao = new KaryawanDao(); 
            List<KaryawanModel> listKaryawan = karyawanDao.getAllData("", false); 

            for (KaryawanModel k : listKaryawan) {
                comboKaryawan.addItem(k); 
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        labelGPokok1 = new javax.swing.JLabel();
        inputId = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        labelGPokok = new javax.swing.JLabel();
        inputGPokok = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        labelGolongan3 = new javax.swing.JLabel();
        comboKaryawan = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        labelTunjanganMakan = new javax.swing.JLabel();
        inputTunjanganMakan = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        labelTunjanganLembur = new javax.swing.JLabel();
        inputTunjanganLembur = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        labelTunjanganJabatan = new javax.swing.JLabel();
        inputTunjanganJabatan = new javax.swing.JTextField();
        jPanel20 = new javax.swing.JPanel();
        labelTunjanganLembur3 = new javax.swing.JLabel();
        inputJumlahLembur = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        labelTunjanganTransportasi = new javax.swing.JLabel();
        inputTunjanganTransportasi = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        labelTunjanganTransportasi3 = new javax.swing.JLabel();
        inputJht = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        labelTunjanganTransportasi2 = new javax.swing.JLabel();
        inputJkm = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        labelTunjanganTransportasi1 = new javax.swing.JLabel();
        inputJkk = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        save = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        title.setText("Data Gaji Kotor");

        jPanel1.setMaximumSize(new java.awt.Dimension(830, 384));
        jPanel1.setMinimumSize(new java.awt.Dimension(830, 384));

        jPanel3.setLayout(new java.awt.GridLayout(1, 0, 30, 0));

        labelGPokok1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelGPokok1.setText("ID");

        inputId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inputId)
            .addComponent(labelGPokok1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(labelGPokok1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(jPanel7);
        jPanel7.getAccessibleContext().setAccessibleName("");

        labelGPokok.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelGPokok.setText("Gaji Pokok");

        inputGPokok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputGPokokActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inputGPokok)
            .addComponent(labelGPokok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(labelGPokok)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputGPokok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(jPanel4);

        labelGolongan3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelGolongan3.setText("Nama Karyawan");

        comboKaryawan.setToolTipText("");
        comboKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboKaryawanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelGolongan3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(comboKaryawan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(labelGolongan3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel11);

        jPanel5.setLayout(new java.awt.GridLayout(1, 0, 30, 0));

        jPanel14.setMaximumSize(new java.awt.Dimension(120, 55));
        jPanel14.setPreferredSize(new java.awt.Dimension(120, 55));

        labelTunjanganMakan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTunjanganMakan.setText("T. Makan");

        inputTunjanganMakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTunjanganMakanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inputTunjanganMakan)
            .addComponent(labelTunjanganMakan, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(labelTunjanganMakan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputTunjanganMakan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel14);
        jPanel14.getAccessibleContext().setAccessibleName("");

        jPanel19.setMaximumSize(new java.awt.Dimension(110, 55));
        jPanel19.setPreferredSize(new java.awt.Dimension(110, 55));

        labelTunjanganLembur.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTunjanganLembur.setText("T. Lembur");

        inputTunjanganLembur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTunjanganLemburActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inputTunjanganLembur)
            .addComponent(labelTunjanganLembur, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addComponent(labelTunjanganLembur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputTunjanganLembur))
        );

        jPanel5.add(jPanel19);

        jPanel15.setMaximumSize(new java.awt.Dimension(110, 55));
        jPanel15.setPreferredSize(new java.awt.Dimension(110, 55));

        labelTunjanganJabatan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTunjanganJabatan.setText("T. Jabatan");

        inputTunjanganJabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTunjanganJabatanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inputTunjanganJabatan)
            .addComponent(labelTunjanganJabatan, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(labelTunjanganJabatan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputTunjanganJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.add(jPanel15);

        jPanel20.setMaximumSize(new java.awt.Dimension(30, 55));

        labelTunjanganLembur3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTunjanganLembur3.setText("Jam Lembur");

        inputJumlahLembur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputJumlahLemburActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inputJumlahLembur)
            .addComponent(labelTunjanganLembur3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addComponent(labelTunjanganLembur3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputJumlahLembur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.add(jPanel20);
        jPanel20.getAccessibleContext().setAccessibleDescription("");

        jPanel10.setMaximumSize(new java.awt.Dimension(18, 32767));
        jPanel10.setName(""); // NOI18N
        jPanel10.setPreferredSize(new java.awt.Dimension(18, 55));

        labelTunjanganTransportasi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTunjanganTransportasi.setText("T. Transportasi");

        inputTunjanganTransportasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTunjanganTransportasiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTunjanganTransportasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(inputTunjanganTransportasi)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(labelTunjanganTransportasi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputTunjanganTransportasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.add(jPanel10);

        jPanel6.setLayout(new java.awt.GridLayout(1, 0, 30, 0));

        jPanel16.setName(""); // NOI18N

        labelTunjanganTransportasi3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTunjanganTransportasi3.setText("JHT Perusahaan");

        inputJht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputJhtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTunjanganTransportasi3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(inputJht)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addComponent(labelTunjanganTransportasi3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputJht, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel6.add(jPanel16);

        jPanel13.setName(""); // NOI18N

        labelTunjanganTransportasi2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTunjanganTransportasi2.setText("JKM");

        inputJkm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputJkmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTunjanganTransportasi2, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
            .addComponent(inputJkm)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(labelTunjanganTransportasi2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputJkm, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanel6.add(jPanel13);

        jPanel12.setName(""); // NOI18N
        jPanel12.setPreferredSize(new java.awt.Dimension(125, 55));

        labelTunjanganTransportasi1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTunjanganTransportasi1.setText("JKK");

        inputJkk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputJkkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTunjanganTransportasi1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(inputJkk)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(labelTunjanganTransportasi1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputJkk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel6.add(jPanel12);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        save.setText("Save");
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMouseClicked(evt);
            }
        });

        edit.setText("Edit");
        edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        delete.setText("Delete");
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title)
            .addGroup(layout.createSequentialGroup()
                .addComponent(save)
                .addGap(0, 0, 0)
                .addComponent(edit)
                .addGap(18, 18, 18)
                .addComponent(delete))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(title)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save)
                    .addComponent(edit)
                    .addComponent(delete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editActionPerformed

    private void saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseClicked
//        String nama = inputNama.getText();
        String g_pokok = inputGPokok.getText();
        String t_transportasi = inputTunjanganTransportasi.getText();
        String t_makan = inputTunjanganMakan.getText();
        String t_lembur = inputTunjanganJabatan.getText();
//        String p_absen = inputPotongaAbsen.getText();
        JabatanModel jabatan = (JabatanModel) comboKaryawan.getSelectedItem();        
        
        int g_pokok_final;
        int t_transportasi_final;
        int t_makan_final;
        int t_lembur_final;
        int p_absen_final;

        try {
            g_pokok_final = Integer.parseInt(g_pokok);
            t_transportasi_final = Integer.parseInt(t_transportasi);
            t_makan_final = Integer.parseInt(t_makan);
            t_lembur_final = Integer.parseInt(t_lembur);
//            p_absen_final = Integer.parseInt(p_absen);
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Gaji, Tunjangan, & Potongan harus angka");
            return;
        }

        KaryawanModel model = new KaryawanModel();
//        model.setNama(nama);
        model.setGajiPokok(g_pokok_final);
        model.setTunjanganTransportasi(t_transportasi_final);
        model.setTunjanganMakan(t_makan_final);
        model.setTunjanganLembur(t_lembur_final);
//        model.setPotonganAbsen(p_absen_final);
        model.setJabatanId(jabatan.getId());


        KaryawanDao karyawanDao = new KaryawanDao();

        if (karyawanDao.saveData(model)) {
            panel.loadTable("");
            dispose();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
        } else {
            JOptionPane.showMessageDialog(null, "Gagal menyimpan data");
        }
    }//GEN-LAST:event_saveMouseClicked

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        Long id = Long.parseLong(
            inputId.getText()
                .toString()
                .replace("#", "")
        );

        KaryawanDao kary = new KaryawanDao();

        if (kary.deleteData(id)) {
            panel.loadTable("");
            dispose();
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
        } else {
            JOptionPane.showMessageDialog(null, "Gagal menghapus data");
        }
    }//GEN-LAST:event_deleteMouseClicked

    private void editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseClicked
        Long id = Long.parseLong(
            inputId.getText()
                .toString()
                .replace("#", "")
        );
        
//        String nama = inputNama.getText();
        String g_pokok = inputGPokok.getText();
        String t_transportasi = inputTunjanganTransportasi.getText();
        String t_makan = inputTunjanganMakan.getText();
        String t_lembur = inputTunjanganJabatan.getText();
//        String p_absen = inputPotongaAbsen.getText();
        JabatanModel jabatan = (JabatanModel) comboKaryawan.getSelectedItem();        
        
        int g_pokok_final;
        int t_transportasi_final;
        int t_makan_final;
        int t_lembur_final;
//        int p_absen_final;

        try {
            g_pokok_final = Integer.parseInt(g_pokok);
            t_transportasi_final = Integer.parseInt(t_transportasi);
            t_makan_final = Integer.parseInt(t_makan);
            t_lembur_final = Integer.parseInt(t_lembur);
//            p_absen_final = Integer.parseInt(p_absen);
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Gaji, Tunjangan, & Potongan harus angka");
            return;
        }

        KaryawanModel model = new KaryawanModel();
        model.setId(id);
//        model.setNama(nama);
        model.setGajiPokok(g_pokok_final);
        model.setTunjanganTransportasi(t_transportasi_final);
        model.setTunjanganMakan(t_makan_final);
        model.setTunjanganLembur(t_lembur_final);
//        model.setPotonganAbsen(p_absen_final);
        model.setJabatanId(jabatan.getId());

        KaryawanDao karDao = new KaryawanDao();

        if (karDao.editData(model)) {
            panel.loadTable("");
            dispose();
            JOptionPane.showMessageDialog(null, "Data berhasil diedit");
        } else {
            JOptionPane.showMessageDialog(null, "Gagal mengedit data");
        }
    }//GEN-LAST:event_editMouseClicked

    private void inputJumlahLemburActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputJumlahLemburActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputJumlahLemburActionPerformed

    private void inputTunjanganLemburActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTunjanganLemburActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTunjanganLemburActionPerformed

    private void inputTunjanganJabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTunjanganJabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTunjanganJabatanActionPerformed

    private void inputTunjanganMakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTunjanganMakanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTunjanganMakanActionPerformed

    private void inputTunjanganTransportasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTunjanganTransportasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTunjanganTransportasiActionPerformed

    private void inputGPokokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputGPokokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputGPokokActionPerformed

    private void comboKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboKaryawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboKaryawanActionPerformed

    private void inputIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputIdActionPerformed

    private void inputJkkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputJkkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputJkkActionPerformed

    private void inputJkmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputJkmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputJkmActionPerformed

    private void inputJhtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputJhtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputJhtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GajiKotorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GajiKotorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GajiKotorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GajiKotorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        GajiKotor panel = new GajiKotor();

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GajiKotorDialog dialog = new GajiKotorDialog(new javax.swing.JFrame(), true, "", 0L, panel);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<KaryawanModel> comboKaryawan;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JTextField inputGPokok;
    private javax.swing.JTextField inputId;
    private javax.swing.JTextField inputJht;
    private javax.swing.JTextField inputJkk;
    private javax.swing.JTextField inputJkm;
    private javax.swing.JTextField inputJumlahLembur;
    private javax.swing.JTextField inputTunjanganJabatan;
    private javax.swing.JTextField inputTunjanganLembur;
    private javax.swing.JTextField inputTunjanganLembur1;
    private javax.swing.JTextField inputTunjanganMakan;
    private javax.swing.JTextField inputTunjanganTransportasi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel labelGPokok;
    private javax.swing.JLabel labelGPokok1;
    private javax.swing.JLabel labelGolongan3;
    private javax.swing.JLabel labelTunjanganJabatan;
    private javax.swing.JLabel labelTunjanganLembur;
    private javax.swing.JLabel labelTunjanganLembur1;
    private javax.swing.JLabel labelTunjanganLembur3;
    private javax.swing.JLabel labelTunjanganMakan;
    private javax.swing.JLabel labelTunjanganTransportasi;
    private javax.swing.JLabel labelTunjanganTransportasi1;
    private javax.swing.JLabel labelTunjanganTransportasi2;
    private javax.swing.JLabel labelTunjanganTransportasi3;
    private javax.swing.JButton save;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
