/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penggajian.dialog;

import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import penggajian.dao.JabatanDao;
import penggajian.dao.KaryawanDao;
import penggajian.helper.BaseSetting;
import penggajian.model.JabatanModel;
import penggajian.model.KaryawanModel;
import penggajian.page.dashboard.Karyawan;

/**
 *
 * @author Dion
 */
public class KaryawanDialog extends javax.swing.JDialog {
    private Karyawan panel;
    /**
     * Creates new form JabatanDialog
     */
    public KaryawanDialog(java.awt.Frame parent, boolean modal, String typeDialog, Long id, Karyawan panel) {
        super(parent, modal);
        this.panel = panel;
        initComponents();
        
        BaseSetting.setTitlePanel(title);
        title.setText(
            typeDialog + " " + title.getText()
        );
        
        BaseSetting.setInput(inputId);
        inputId.setEditable(false);
        BaseSetting.setInput(inputNama);
        BaseSetting.setInput(inputGPokok);
        BaseSetting.setInput(inputNpwp);
        BaseSetting.setInput(inputTunjanganTransportasi);
        BaseSetting.setInput(inputTunjanganMakan);
        BaseSetting.setInput(inputTunjanganLembur);
        BaseSetting.setInput(inputPotongaAbsen);
        BaseSetting.setCombo(comboGolongan);
        BaseSetting.setCombo(comboJabatan);
        loadComboJabatan();
        
        
        BaseSetting.setButton(save);
        BaseSetting.setButton(edit);
        BaseSetting.setButton(delete);

        if(typeDialog.equals("Edit")){
            save.setVisible(false);
            edit.setVisible(true);
            delete.setVisible(true);
            
            KaryawanDao karyawanDao = new KaryawanDao();

            KaryawanModel t = karyawanDao.getById(id);
            inputId.setText("#" + t.getId());
            inputNama.setText(t.getNama());
            inputGPokok.setText("" + t.getGajiPokok());
            inputNpwp.setText(t.getNpwp());

            inputTunjanganTransportasi.setText("" + t.getTunjanganTransportasi());
            inputTunjanganMakan.setText("" + t.getTunjanganMakan());
            inputTunjanganLembur.setText("" + t.getTunjanganLembur());
            inputPotongaAbsen.setText("" + t.getPotonganAbsen());
            comboGolongan.setSelectedItem(t.getGolonganTer());
                       
            JabatanModel target = t.getJabatanModel();

            for (int i = 0; i < comboJabatan.getItemCount(); i++) {
                JabatanModel item = comboJabatan.getItemAt(i);

                if (item.getId() == target.getId()) {
                    comboJabatan.setSelectedIndex(i);
                    break;
                }
            }


        }else{
            save.setVisible(true);
            edit.setVisible(false);
            delete.setVisible(false);
        }
    }
    
    private void loadComboJabatan() {
        comboJabatan.removeAllItems();

        try {
            JabatanDao jabatanDao = new JabatanDao(); 
            List<JabatanModel> listJabatan = jabatanDao.getAllData(""); 

            for (JabatanModel j : listJabatan) {
                comboJabatan.addItem(j); 
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        labelId = new javax.swing.JLabel();
        inputId = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        labelNama = new javax.swing.JLabel();
        inputNama = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        labelGPokok = new javax.swing.JLabel();
        inputGPokok = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        labelNpwp = new javax.swing.JLabel();
        inputNpwp = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        labelTunjanganTransportasi = new javax.swing.JLabel();
        inputTunjanganTransportasi = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        labelTunjanganMakan = new javax.swing.JLabel();
        inputTunjanganMakan = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        labelTunjanganLembur = new javax.swing.JLabel();
        inputTunjanganLembur = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        labelPotongaAbsen = new javax.swing.JLabel();
        inputPotongaAbsen = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        labelGolongan = new javax.swing.JLabel();
        comboGolongan = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        labelJabatan = new javax.swing.JLabel();
        comboJabatan = new javax.swing.JComboBox<>();
        save = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        title.setText("Data Karyawan");

        labelId.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelId.setText("Id");

        inputId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inputId)
            .addComponent(labelId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(labelId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        labelNama.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelNama.setText("Nama");

        inputNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNamaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inputNama)
            .addComponent(labelNama, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(labelNama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        labelGPokok.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelGPokok.setText("Gaji Pokok");

        inputGPokok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputGPokokActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inputGPokok)
            .addComponent(labelGPokok, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(labelGPokok)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputGPokok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        labelNpwp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelNpwp.setText("NPWP");

        inputNpwp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNpwpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inputNpwp)
            .addComponent(labelNpwp, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(labelNpwp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputNpwp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        labelTunjanganTransportasi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTunjanganTransportasi.setText("Tunjangan Transportasi");

        inputTunjanganTransportasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTunjanganTransportasiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inputTunjanganTransportasi)
            .addComponent(labelTunjanganTransportasi, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(labelTunjanganTransportasi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputTunjanganTransportasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        labelTunjanganMakan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTunjanganMakan.setText("Tunjangan Makan");

        inputTunjanganMakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTunjanganMakanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inputTunjanganMakan)
            .addComponent(labelTunjanganMakan, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(labelTunjanganMakan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputTunjanganMakan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        labelTunjanganLembur.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTunjanganLembur.setText("Tunjangan Lembur");

        inputTunjanganLembur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTunjanganLemburActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inputTunjanganLembur)
            .addComponent(labelTunjanganLembur, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(labelTunjanganLembur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputTunjanganLembur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        labelPotongaAbsen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelPotongaAbsen.setText("Potongan Absen");

        inputPotongaAbsen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPotongaAbsenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inputPotongaAbsen)
            .addComponent(labelPotongaAbsen, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(labelPotongaAbsen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputPotongaAbsen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        labelGolongan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelGolongan.setText("Golongan TER");

        comboGolongan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C" }));
        comboGolongan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboGolonganActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelGolongan, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
            .addComponent(comboGolongan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(labelGolongan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboGolongan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        labelJabatan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelJabatan.setText("Jabatan");

        comboJabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboJabatanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelJabatan, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
            .addComponent(comboJabatan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(labelJabatan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        save.setText("Save");
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMouseClicked(evt);
            }
        });

        edit.setText("Edit");
        edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        delete.setText("Delete");
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(save)
                        .addGap(0, 0, 0)
                        .addComponent(edit)
                        .addGap(18, 18, 18)
                        .addComponent(delete)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(title)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save)
                    .addComponent(edit)
                    .addComponent(delete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputIdActionPerformed

    private void inputGPokokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputGPokokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputGPokokActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editActionPerformed

    private void saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseClicked
        String nama = inputNama.getText();
        String g_pokok = inputGPokok.getText();
        String npwp = inputNpwp.getText();
        String t_transportasi = inputTunjanganTransportasi.getText();
        String t_makan = inputTunjanganMakan.getText();
        String t_lembur = inputTunjanganLembur.getText();
        String p_absen = inputPotongaAbsen.getText();
        String golongan = comboGolongan.getSelectedItem().toString();
        JabatanModel jabatan = (JabatanModel) comboJabatan.getSelectedItem();        
        
        int g_pokok_final;
        int t_transportasi_final;
        int t_makan_final;
        int t_lembur_final;
        int p_absen_final;

        try {
            g_pokok_final = Integer.parseInt(g_pokok);
            t_transportasi_final = Integer.parseInt(t_transportasi);
            t_makan_final = Integer.parseInt(t_makan);
            t_lembur_final = Integer.parseInt(t_lembur);
            p_absen_final = Integer.parseInt(p_absen);
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Gaji, Tunjangan, & Potongan harus angka");
            return;
        }

        KaryawanModel model = new KaryawanModel();
        model.setNama(nama);
        model.setGajiPokok(g_pokok_final);
        model.setNpwp(npwp);
        model.setTunjanganTransportasi(t_transportasi_final);
        model.setTunjanganMakan(t_makan_final);
        model.setTunjanganLembur(t_lembur_final);
        model.setPotonganAbsen(p_absen_final);
        model.setGolonganTer(golongan);
        model.setJabatanId(jabatan.getId());


        KaryawanDao karyawanDao = new KaryawanDao();

        if (karyawanDao.saveData(model)) {
            panel.loadTable("");
            dispose();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
        } else {
            JOptionPane.showMessageDialog(null, "Gagal menyimpan data");
        }
    }//GEN-LAST:event_saveMouseClicked

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        Long id = Long.parseLong(
            inputId.getText()
                .toString()
                .replace("#", "")
        );

        KaryawanDao kary = new KaryawanDao();

        if (kary.deleteData(id)) {
            panel.loadTable("");
            dispose();
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
        } else {
            JOptionPane.showMessageDialog(null, "Gagal menghapus data");
        }
    }//GEN-LAST:event_deleteMouseClicked

    private void editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseClicked
        Long id = Long.parseLong(
            inputId.getText()
                .toString()
                .replace("#", "")
        );
        
        String nama = inputNama.getText();
        String g_pokok = inputGPokok.getText();
        String npwp = inputNpwp.getText();
        String t_transportasi = inputTunjanganTransportasi.getText();
        String t_makan = inputTunjanganMakan.getText();
        String t_lembur = inputTunjanganLembur.getText();
        String p_absen = inputPotongaAbsen.getText();
        String golongan = comboGolongan.getSelectedItem().toString();
        JabatanModel jabatan = (JabatanModel) comboJabatan.getSelectedItem();        
        
        int g_pokok_final;
        int t_transportasi_final;
        int t_makan_final;
        int t_lembur_final;
        int p_absen_final;

        try {
            g_pokok_final = Integer.parseInt(g_pokok);
            t_transportasi_final = Integer.parseInt(t_transportasi);
            t_makan_final = Integer.parseInt(t_makan);
            t_lembur_final = Integer.parseInt(t_lembur);
            p_absen_final = Integer.parseInt(p_absen);
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Gaji, Tunjangan, & Potongan harus angka");
            return;
        }

        KaryawanModel model = new KaryawanModel();
        model.setId(id);
        model.setNama(nama);
        model.setGajiPokok(g_pokok_final);
        model.setNpwp(npwp);
        model.setTunjanganTransportasi(t_transportasi_final);
        model.setTunjanganMakan(t_makan_final);
        model.setTunjanganLembur(t_lembur_final);
        model.setPotonganAbsen(p_absen_final);
        model.setGolonganTer(golongan);
        model.setJabatanId(jabatan.getId());

        KaryawanDao karDao = new KaryawanDao();

        if (karDao.editData(model)) {
            panel.loadTable("");
            dispose();
            JOptionPane.showMessageDialog(null, "Data berhasil diedit");
        } else {
            JOptionPane.showMessageDialog(null, "Gagal mengedit data");
        }
    }//GEN-LAST:event_editMouseClicked

    private void inputNpwpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNpwpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNpwpActionPerformed

    private void inputTunjanganTransportasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTunjanganTransportasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTunjanganTransportasiActionPerformed

    private void comboGolonganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboGolonganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboGolonganActionPerformed

    private void inputNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNamaActionPerformed

    private void inputTunjanganMakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTunjanganMakanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTunjanganMakanActionPerformed

    private void inputTunjanganLemburActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTunjanganLemburActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTunjanganLemburActionPerformed

    private void inputPotongaAbsenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPotongaAbsenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPotongaAbsenActionPerformed

    private void comboJabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboJabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboJabatanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KaryawanDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KaryawanDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KaryawanDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KaryawanDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        Karyawan panel = new Karyawan();

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                KaryawanDialog dialog = new KaryawanDialog(new javax.swing.JFrame(), true, "", 0L, panel);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboGolongan;
    private javax.swing.JComboBox<JabatanModel> comboJabatan;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JTextField inputGPokok;
    private javax.swing.JTextField inputId;
    private javax.swing.JTextField inputNama;
    private javax.swing.JTextField inputNpwp;
    private javax.swing.JTextField inputPotongaAbsen;
    private javax.swing.JTextField inputTunjanganLembur;
    private javax.swing.JTextField inputTunjanganMakan;
    private javax.swing.JTextField inputTunjanganTransportasi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel labelGPokok;
    private javax.swing.JLabel labelGolongan;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelJabatan;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelNpwp;
    private javax.swing.JLabel labelPotongaAbsen;
    private javax.swing.JLabel labelTunjanganLembur;
    private javax.swing.JLabel labelTunjanganMakan;
    private javax.swing.JLabel labelTunjanganTransportasi;
    private javax.swing.JButton save;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
